medicines_300 = [
    {
        "name": "人参",
        "alias": "黄参、地精、神草",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、微苦",
        "meridian": "归脾、肺、心经",
        "efficacy": "大补元气，复脉固脱，补脾益肺，生津，安神",
        "indications": "体虚欲脱，肢冷脉微,脾虚食少,肺虚喘咳,津伤口渴,内热消渴,久病虚羸,惊悸失眠,阳痿宫冷",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "实证、热证而正气不虚者忌服",
        "quantity": 500,
        "unit": "g",
        "price": 85,
        "min_stock": 50,
        "notes": "一等选装人参"
    },
    {
        "name": "黄芪",
        "alias": "黄耆",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "补气升阳，固表止汗,利水消肿,生津养血,行滞通痹,托毒排脓,敛疮生肌",
        "indications": "气虚乏力,食少便溏,中气下陷,久泻脱肛,便血崩漏,表虚自汗,气虚水肿,内热消渴,血虚萎黄,半身不遂,痹痛麻木,痈疽难溃,久溃不敛",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "表实邪盛,气滞湿阻,食积停滞,痈疽初起或溃后热毒尚盛等实证,以及阴虚阳亢者,均须禁服",
        "quantity": 600,
        "unit": "g",
        "price": 42,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "当归",
        "alias": "干归",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、辛",
        "meridian": "归肝、心、脾经",
        "efficacy": "补血活血,调经止痛,润肠通便",
        "indications": "血虚萎黄,眩晕心悸,月经不调,经闭痛经,虚寒腹痛,风湿痹痛,跌扑损伤,痈疽疮疡,肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "湿阻中满及大便溏泄者慎服",
        "quantity": 450,
        "unit": "g",
        "price": 58,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "白芍",
        "alias": "白芍药",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "苦、酸",
        "meridian": "归肝、脾经",
        "efficacy": "养血调经,敛阴止汗,柔肝止痛",
        "indications": "血虚萎黄,月经不调,崩漏,自汗,盗汗,头痛眩晕,胁痛腹痛,四肢挛急,面色苍白",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阳衰虚寒之证不宜用",
        "quantity": 400,
        "unit": "g",
        "price": 65,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "熟地黄",
        "alias": "熟地",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补血滋阴,益精填髓",
        "indications": "血虚萎黄,眩晕心悸,月经不调,崩漏,肾虚喘咳,须发早白,消渴,便秘,肾虚腰痛",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "脾虚湿滞,腹满便溏,痰多者不宜使用",
        "quantity": 350,
        "unit": "g",
        "price": 75,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "党参",
        "alias": "上党参、中灵参",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "补中益气,健脾益肺,养血生津",
        "indications": "脾肺气虚,食少便溏,四肢乏力,气血两亏,久泻脱肛,血虚萎黄",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "不宜与藜芦同用",
        "quantity": 550,
        "unit": "g",
        "price": 38,
        "min_stock": 55,
        "notes": ""
    },
    {
        "name": "白术",
        "alias": "于术、浙术",
        "category": "补虚药",
        "nature": "温",
        "taste": "苦、甘",
        "meridian": "归脾、胃经",
        "efficacy": "健脾益气,燥湿利水,止汗,安胎",
        "indications": "脾虚食少,腹胀泄泻,痰饮眩悸,水肿,自汗,胎动不安",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "阴虚内热,津枯液燥者慎用",
        "quantity": 500,
        "unit": "g",
        "price": 35,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "茯苓",
        "alias": "云苓、松苓",
        "category": "利水渗湿药",
        "nature": "平",
        "taste": "甘、淡",
        "meridian": "归心、脾、肾经",
        "efficacy": "利水渗湿,健脾宁心",
        "indications": "水肿尿少,痰饮眩悸,脾虚食少,便溏泄泻,心神不安,惊悸失眠",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "阴虚而无湿热者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 32,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "甘草",
        "alias": "国老、甜草",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肺、脾、胃经",
        "efficacy": "补脾益气,清热解毒,祛痰止咳,缓急止痛",
        "indications": "脾胃虚弱,倦怠乏力,心悸气短,咳嗽痰多,脘腹四肢挛急疼痛,痈肿疮毒",
        "usage": "煎服",
        "dosage": "2-10g",
        "contraindication": "不宜与京大戟、芫花、甘遂同用",
        "quantity": 600,
        "unit": "g",
        "price": 25,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "金银花",
        "alias": "忍冬花、银花、双花",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、心、胃经",
        "efficacy": "清热解毒,疏散风热",
        "indications": "痈肿疔疮,喉痹,丹毒,热毒血痢,风热感冒,温病发热",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚疮疡脓清者不宜使用",
        "quantity": 400,
        "unit": "g",
        "price": 45,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "连翘",
        "alias": "连壳、黄花条",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归肺、心、小肠经",
        "efficacy": "清热解毒,消肿散结,疏散风热",
        "indications": "痈疽,瘰疬,乳痈,丹毒,风热感冒,温病初起,热入营血,高热烦渴",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚脓清者不宜使用",
        "quantity": 350,
        "unit": "g",
        "price": 42,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "板蓝根",
        "alias": "大青根、蓝靛根",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、胃经",
        "efficacy": "清热解毒,凉血利咽",
        "indications": "温毒发斑,舌绛紫暗,烂喉丹痄,大头瘟疫",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 28,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "蒲公英",
        "alias": "黄花地丁、婆婆丁",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肝、胃经",
        "efficacy": "清热解毒,消肿散结,利尿通淋",
        "indications": "疔疮肿毒,乳痈,肺痈,肠痈,湿热黄疸,热淋涩痛",
        "usage": "煎服",
        "dosage": "10-30g",
        "contraindication": "用量过大可致缓泻",
        "quantity": 350,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "黄芩",
        "alias": "条芩、子芩",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、胆、脾、大肠经",
        "efficacy": "清热燥湿,泻火解毒,止血安胎",
        "indications": "湿温、暑湿,胸闷呕恶,湿热痞满,泻痢,黄疸,肺热咳嗽,高热烦渴,血热吐衄,胎动不安",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 38,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "黄连",
        "alias": "川连、味连",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、脾、胃、肝、胆、大肠经",
        "efficacy": "清热燥湿,泻火解毒",
        "indications": "湿热痞满,呕吐吞酸,泻痢,黄疸,高热神昏,心火亢盛,心烦不寐,血热吐衄,目赤牙痛,消渴,痈肿疔疮",
        "usage": "煎服",
        "dosage": "2-5g",
        "contraindication": "脾胃虚寒者慎用,阴虚津伤者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 85,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "黄柏",
        "alias": "川柏、关黄柏",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肾、膀胱经",
        "efficacy": "清热燥湿,泻火除蒸,解毒疗疮",
        "indications": "湿热泻痢,黄疸,带下,热淋,脚气,痿软,盗汗,遗精,疮疡肿毒,湿疹瘙痒",
        "usage": "煎服",
        "dosage": "3-12g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 45,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "麻黄",
        "alias": "龙沙、狗骨",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、微苦",
        "meridian": "归肺、膀胱经",
        "efficacy": "发汗解表,宣肺平喘,利水消肿",
        "indications": "风寒感冒,胸闷喘咳,风水浮肿,支气管哮喘",
        "usage": "煎服",
        "dosage": "2-9g",
        "contraindication": "体虚自汗,盗汗,虚喘者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "桂枝",
        "alias": "柳桂",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、甘",
        "meridian": "归心、肺、膀胱经",
        "efficacy": "发汗解肌,温通经脉,助阳化气,平冲降逆",
        "indications": "风寒感冒,脘腹冷痛,血寒经闭,关节痹痛,痰饮水肿,心悸",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "热病高热,阴虚火旺,血热妄行者忌用",
        "quantity": 450,
        "unit": "g",
        "price": 28,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "柴胡",
        "alias": "茈胡、北柴胡",
        "category": "解表药",
        "nature": "微寒",
        "taste": "苦、辛",
        "meridian": "归肝、胆经",
        "efficacy": "疏散退热,疏肝解郁,升举阳气",
        "indications": "感冒发热,寒热往来,胸胁胀痛,月经不调,子宫脱垂,脱肛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "肝阳上亢,气机上逆者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 35,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "川芎",
        "alias": "芎藭",
        "category": "活血化瘀药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肝、胆、心包经",
        "efficacy": "活血行气,祛风止痛",
        "indications": "月经不调,经闭痛经,产后瘀滞腹痛,胸胁刺痛,跌扑损伤,头痛,风湿痹痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚火旺,上盛下虚及气弱者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 42,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "丹参",
        "alias": "红参、血参",
        "category": "活血化瘀药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归心、心包、肝经",
        "efficacy": "活血祛瘀,通经止痛,清心除烦,凉血消痈",
        "indications": "月经不调,经闭痛经,胸腹刺痛,热痹疼痛,疮疡肿痛,心烦不眠",
        "usage": "煎服",
        "dosage": "5-15g",
        "contraindication": "孕妇慎用",
        "quantity": 450,
        "unit": "g",
        "price": 48,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "红花",
        "alias": "红蓝花、刺红花",
        "category": "活血化瘀药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归心、肝经",
        "efficacy": "活血通经,祛瘀止痛",
        "indications": "经闭,痛经,恶露不行,胸痹心痛,瘀滞腹痛,跌打损伤,疮疡肿痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "孕妇慎用",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "桃仁",
        "alias": "桃核仁",
        "category": "活血化瘀药",
        "nature": "平",
        "taste": "苦、甘",
        "meridian": "归心、肝、大肠经",
        "efficacy": "活血祛瘀,润肠通便",
        "indications": "经闭痛经,癥瘕痞块,跌打损伤,肠燥便秘",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "孕妇慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "半夏",
        "alias": "三叶半夏、三步跳",
        "category": "化痰止咳平喘药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃、肺经",
        "efficacy": "燥湿化痰,降逆止呕",
        "indications": "湿痰寒痰,咳喘痰多,痰饮眩悸,风痰眩晕,痰厥头痛,呕吐反胃",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "阴虚燥咳,津伤口渴,血证者忌用",
        "quantity": 400,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "陈皮",
        "alias": "橘皮、广陈皮",
        "category": "理气药",
        "nature": "温",
        "taste": "苦、辛",
        "meridian": "归脾、肺经",
        "efficacy": "理气健脾,燥湿化痰",
        "indications": "胸脘胀满,食少吐泻,咳嗽痰多",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "气虚体燥,阴虚燥咳者慎用",
        "quantity": 500,
        "unit": "g",
        "price": 22,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "枳实",
        "alias": "酸橙子、枳壳",
        "category": "理气药",
        "nature": "微寒",
        "taste": "苦、辛",
        "meridian": "归脾、胃、大肠经",
        "efficacy": "破气消积,化痰散痞",
        "indications": "积滞内停,痞满胀痛,泻痢后重,大便不通,痰滞胸脘,胸痹",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "脾胃虚弱及孕妇慎用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "山楂",
        "alias": "山里红果、红果",
        "category": "消食药",
        "nature": "微温",
        "taste": "酸、甘",
        "meridian": "归脾、胃、肝经",
        "efficacy": "消食健胃,行气散瘀",
        "indications": "肉食积滞,胃脘胀满,泻痢腹痛,瘀血经闭,产后瘀阻,心腹刺痛",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚弱者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "神曲",
        "alias": "六神曲、建曲",
        "category": "消食药",
        "nature": "温",
        "taste": "甘、辛",
        "meridian": "归脾、胃经",
        "efficacy": "消食化积,健脾和胃",
        "indications": "饮食停滞,消化不良,胸痞腹胀,呕吐泻痢",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾阴虚者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 15,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "麦芽",
        "alias": "大麦芽、麦糵",
        "category": "消食药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、胃经",
        "efficacy": "消食健胃,回乳消胀",
        "indications": "食积不消,脘腹胀痛,脾虚食少,乳汁郁积,乳房胀痛",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "哺乳期妇女慎用",
        "quantity": 350,
        "unit": "g",
        "price": 12,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "酸枣仁",
        "alias": "枣仁、酸枣核",
        "category": "安神药",
        "nature": "平",
        "taste": "甘、酸",
        "meridian": "归心、肝、胆经",
        "efficacy": "养心补肝,宁心安神,敛汗",
        "indications": "虚烦不眠,惊悸多梦,体虚多汗",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "实邪郁火者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 55,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "柏子仁",
        "alias": "柏实、侧柏子",
        "category": "安神药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肾、大肠经",
        "efficacy": "养心安神,润肠通便",
        "indications": "虚烦失眠,心悸怔忡,阴伤便秘",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "便溏者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 42,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "远志",
        "alias": "小草、细草",
        "category": "安神药",
        "nature": "温",
        "taste": "苦、辛",
        "meridian": "归心、肾、肺经",
        "efficacy": "安神益智,祛痰消肿",
        "indications": "心肾不交,失眠多梦,健忘惊悸,咳痰不爽,疮疡肿毒",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "胃炎及胃溃疡者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 38,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "天麻",
        "alias": "赤箭、定风草",
        "category": "平肝息风药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肝经",
        "efficacy": "息风止痉,平抑肝阳,祛风通络",
        "indications": "肝风内动,眩晕头痛,肢体麻木,手足不遂,风湿痹痛",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "气血虚甚者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 185,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "钩藤",
        "alias": "勾藤、双钩藤",
        "category": "平肝息风药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归肝、心包经",
        "efficacy": "清热平肝,息风止痉",
        "indications": "肝火上炎,头痛眩晕,肝风内动,惊痫抽搐,妊娠子痫",
        "usage": "煎服",
        "dosage": "3-12g",
        "contraindication": "无特殊禁忌",
        "quantity": 350,
        "unit": "g",
        "price": 48,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "石决明",
        "alias": "鲍鱼壳、九孔石决明",
        "category": "平肝息风药",
        "nature": "寒",
        "taste": "咸",
        "meridian": "归肝经",
        "efficacy": "平肝潜阳,清肝明目",
        "indications": "肝阳上亢,头晕目眩,目赤肿痛,视物昏花",
        "usage": "煎服",
        "dosage": "3-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 65,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "牡蛎",
        "alias": "左牡蛎、海蛎子壳",
        "category": "平肝息风药",
        "nature": "微寒",
        "taste": "咸、涩",
        "meridian": "归肝、胆、肾经",
        "efficacy": "重镇安神,潜阳补阴,软坚散结",
        "indications": "惊悸失眠,眩晕耳鸣,瘰疬痰核,徵瘕痞块",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "体虚有寒者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 35,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "龙骨",
        "alias": "白龙骨、五花龙骨",
        "category": "安神药",
        "nature": "平",
        "taste": "甘、涩",
        "meridian": "归心、肝、肾经",
        "efficacy": "镇惊安神,敛汗固精,止血涩肠",
        "indications": "心悸怔忡,失眠健忘,惊痫癫狂,自汗盗汗,遗精淋浊,崩漏",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "湿热积滞者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 45,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "朱砂",
        "alias": "辰砂、丹砂",
        "category": "安神药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归心经",
        "efficacy": "清心镇惊,安神解毒",
        "indications": "心悸易惊,失眠多梦,癫痫发狂,小儿惊风,疮疡肿毒",
        "usage": "入丸散",
        "dosage": "0.1-0.5g",
        "contraindication": "不宜久服,肝肾功能不全者慎用",
        "quantity": 100,
        "unit": "g",
        "price": 280,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "磁石",
        "alias": "吸铁石、慈石",
        "category": "安神药",
        "nature": "寒",
        "taste": "咸",
        "meridian": "归心、肝、肾经",
        "efficacy": "镇惊安神,平肝潜阳,聪耳明目",
        "indications": "心悸失眠,头晕目眩,惊痫癫狂,耳鸣耳聋,视物昏花",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "琥珀",
        "alias": "血珀、红琥珀",
        "category": "安神药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肝、膀胱经",
        "efficacy": "镇惊安神,活血散瘀,利尿通淋",
        "indications": "惊悸失眠,惊风癫痫,瘀血阻滞,淋证癃闭",
        "usage": "研末冲服",
        "dosage": "1.5-3g",
        "contraindication": "阴虚内热者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 85,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "灵芝",
        "alias": "赤芝、红芝",
        "category": "安神药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肺、肝、肾经",
        "efficacy": "补气安神,止咳平喘",
        "indications": "心神不宁,失眠心悸,肺虚咳喘,虚劳短气",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "实证者慎用",
        "quantity": 250,
        "unit": "g",
        "price": 125,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "合欢皮",
        "alias": "合昏、夜合皮",
        "category": "安神药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肝经",
        "efficacy": "解郁安神,活血消肿",
        "indications": "心神不宁,忧郁失眠,肺痈疮肿,跌打损伤",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "孕妇慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "夜交藤",
        "alias": "首乌藤、何首乌藤",
        "category": "安神药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肝经",
        "efficacy": "养心安神,祛风通络",
        "indications": "失眠多梦,血虚身痛,风湿痹痛,皮肤瘙痒",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "大便溏泄者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "人参叶",
        "alias": "参叶",
        "category": "补虚药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肺、胃经",
        "efficacy": "补气益肺,祛暑生津",
        "indications": "气虚咳嗽,暑热烦躁,津伤口渴",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "实证、热证者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "西洋参",
        "alias": "花旗参、洋参",
        "category": "补虚药",
        "nature": "凉",
        "taste": "苦、微甘",
        "meridian": "归心、肺、肾经",
        "efficacy": "补气养阴,清热生津",
        "indications": "气虚阴亏,虚热烦倦,咳喘痰血,内热消渴",
        "usage": "另煎兑服",
        "dosage": "3-6g",
        "contraindication": "中阳衰微,胃有寒湿者忌用",
        "quantity": 200,
        "unit": "g",
        "price": 320,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "太子参",
        "alias": "孩儿参、童参",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘、微苦",
        "meridian": "归脾、肺经",
        "efficacy": "益气健脾,生津润肺",
        "indications": "脾虚体倦,食欲不振,病后虚弱,阴虚盗汗",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "实证者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 85,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "山药",
        "alias": "怀山药、淮山",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺、肾经",
        "efficacy": "补脾养胃,生津益肺,补肾涩精",
        "indications": "脾虚食少,久泻不止,肺虚喘咳,肾虚遗精,带下尿频",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "湿盛中满者慎用",
        "quantity": 500,
        "unit": "g",
        "price": 28,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "白扁豆",
        "alias": "扁豆、眉豆",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归脾、胃经",
        "efficacy": "健脾化湿,和中消暑",
        "indications": "脾胃虚弱,食欲不振,大便溏泻,白带过多,暑湿吐泻",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "无特殊禁忌",
        "quantity": 400,
        "unit": "g",
        "price": 18,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "大枣",
        "alias": "红枣、干枣",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归脾、胃、心经",
        "efficacy": "补中益气,养血安神",
        "indications": "脾虚食少,乏力便溏,妇人脏躁",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "湿盛脘腹胀满者慎用",
        "quantity": 500,
        "unit": "g",
        "price": 22,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "刺五加",
        "alias": "刺拐棒、老虎镣",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛、微苦",
        "meridian": "归脾、肾、心经",
        "efficacy": "益气健脾,补肾安神",
        "indications": "脾肺气虚,体虚乏力,食欲不振,肾虚腰膝酸软,失眠多梦",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "绞股蓝",
        "alias": "七叶胆、小苦药",
        "category": "补虚药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、脾、肾经",
        "efficacy": "清热解毒,止咳祛痰,补气养阴",
        "indications": "气虚阴亏,肺热咳嗽,痰多黄稠,慢性气管炎",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 28,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "红景天",
        "alias": "蔷薇红景天",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、涩",
        "meridian": "归肺、心经",
        "efficacy": "益气活血,通脉平喘",
        "indications": "气虚血瘀,胸痹心痛,中风偏瘫,倦怠气喘",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 95,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "沙棘",
        "alias": "沙枣、醋柳果",
        "category": "补虚药",
        "nature": "温",
        "taste": "酸、涩",
        "meridian": "归脾、胃、肺、心经",
        "efficacy": "健脾消食,止咳祛痰,活血散瘀",
        "indications": "脾虚食少,食积腹痛,咳嗽痰多,胸痹心痛,跌打损伤",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "体温热甚者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "蜂蜜",
        "alias": "蜜糖、蜂糖",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肺、脾、大肠经",
        "efficacy": "补中润燥,止痛解毒",
        "indications": "脘腹疼痛,肺燥咳嗽,肠燥便秘,目赤口疮,溃疡不敛",
        "usage": "冲服",
        "dosage": "15-30g",
        "contraindication": "湿阻中满,湿热痰滞者慎用",
        "quantity": 500,
        "unit": "g",
        "price": 45,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "鹿茸",
        "alias": "斑龙珠",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、咸",
        "meridian": "归肾、肝经",
        "efficacy": "壮肾阳,益精血,强筋骨,调冲任",
        "indications": "肾阳不足,阳痿滑精,宫冷不孕,羸瘦神疲,畏寒眩晕,耳鸣耳聋,腰脊冷痛",
        "usage": "研末冲服",
        "dosage": "1-2g",
        "contraindication": "阴虚阳亢,血分有热,胃火盛者忌用",
        "quantity": 50,
        "unit": "g",
        "price": 580,
        "min_stock": 5,
        "notes": ""
    },
    {
        "name": "紫河车",
        "alias": "胎盘、人胞",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、咸",
        "meridian": "归肺、肝、肾经",
        "efficacy": "温肾补精,益气养血",
        "indications": "虚劳羸瘦,骨蒸盗汗,咳嗽气喘,食少气短,阳痿遗精,不孕少乳",
        "usage": "研末冲服",
        "dosage": "2-3g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 100,
        "unit": "g",
        "price": 320,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "淫羊藿",
        "alias": "仙灵脾",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛、甘",
        "meridian": "归肝、肾经",
        "efficacy": "补肾阳,强筋骨,祛风湿",
        "indications": "肾阳虚衰,阳痿遗精,筋骨痿软,风湿痹痛,麻木拘挛",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 38,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "巴戟天",
        "alias": "巴戟、鸡肠风",
        "category": "补虚药",
        "nature": "微温",
        "taste": "辛、甘",
        "meridian": "归肾、肝经",
        "efficacy": "补肾阳,强筋骨,祛风湿",
        "indications": "阳痿遗精,宫冷不孕,月经不调,少腹冷痛,风湿痹痛",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "仙茅",
        "alias": "独茅根、地棕根",
        "category": "补虚药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归肾、肝经",
        "efficacy": "补肾阳,强筋骨,祛寒湿",
        "indications": "阳痿精冷,筋骨痿软,腰膝冷痛,阳虚冷泻",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 250,
        "unit": "g",
        "price": 52,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "杜仲",
        "alias": "思仙、木绵",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补肝肾,强筋骨,安胎",
        "indications": "肾虚腰痛,筋骨无力,妊娠漏血,胎动不安,高血压",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 48,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "续断",
        "alias": "川断、接骨草",
        "category": "补虚药",
        "nature": "微温",
        "taste": "苦、辛",
        "meridian": "归肝、肾经",
        "efficacy": "补肝肾,强筋骨,续折伤,止崩漏",
        "indications": "腰膝酸软,风湿痹痛,跌打损伤,崩漏下血,胎动不安",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "痢疾初起者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 35,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "肉苁蓉",
        "alias": "大芸、寸芸",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、咸",
        "meridian": "归肾、大肠经",
        "efficacy": "补肾阳,益精血,润肠通便",
        "indications": "阳痿不孕,腰膝酸软,筋骨无力,肠燥便秘",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "阴虚火旺,大便溏泄者忌用",
        "quantity": 250,
        "unit": "g",
        "price": 85,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "锁阳",
        "alias": "琐阳、不老药",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归肝、肾、大肠经",
        "efficacy": "补肾阳,益精血,润肠通便",
        "indications": "肾阳不足,精血亏虚,腰膝痿软,肠燥便秘",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚火旺,脾虚泄泻者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "补骨脂",
        "alias": "破故纸、故子",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归肾、脾经",
        "efficacy": "补肾壮阳,固精缩尿,温脾止泻",
        "indications": "肾阳不足,阳痿遗精,遗尿尿频,腰膝冷痛,肾虚作喘,五更泄泻",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "益智仁",
        "alias": "益智子",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肾、脾经",
        "efficacy": "温肾固精缩尿,温脾开胃摄唾",
        "indications": "肾虚遗尿,小便频数,遗精白浊,脾胃虚寒,腹痛吐泻,口涎自流",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 300,
        "unit": "g",
        "price": 42,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "菟丝子",
        "alias": "菟丝实、吐丝子",
        "category": "补虚药",
        "nature": "平",
        "taste": "辛、甘",
        "meridian": "归肝、肾、脾经",
        "efficacy": "补肾益精,养肝明目,固精缩尿,止泻安胎",
        "indications": "腰膝酸痛,阳痿遗精,遗尿尿频,目昏耳鸣,脾肾虚泻,胎动不安",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "阴虚火旺,大便燥结者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 38,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "沙苑子",
        "alias": "沙苑蒺藜、潼蒺藜",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补肾固精,养肝明目",
        "indications": "肾虚腰痛,阳痿遗精,遗尿尿频,白带过多,目暗不明",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "蛤蚧",
        "alias": "大壁虎、仙蟾",
        "category": "补虚药",
        "nature": "平",
        "taste": "咸",
        "meridian": "归肺、肾经",
        "efficacy": "补肺益肾,纳气定喘,助阳益精",
        "indications": "虚喘气促,劳嗽咳血,阳痿遗精",
        "usage": "煎服或研末",
        "dosage": "3-6g",
        "contraindication": "风寒咳嗽者忌用",
        "quantity": 100,
        "unit": "g",
        "price": 280,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "核桃仁",
        "alias": "胡桃仁、核桃肉",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归肾、肺、大肠经",
        "efficacy": "补肾温肺,润肠通便",
        "indications": "肾阳不足,腰膝酸软,阳痿遗精,肺虚咳嗽,肠燥便秘",
        "usage": "煎服",
        "dosage": "10-30g",
        "contraindication": "阴虚火旺,痰热咳嗽者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 28,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "冬虫夏草",
        "alias": "虫草、夏草冬虫",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肺、肾经",
        "efficacy": "补肾益肺,止血化痰",
        "indications": "肾虚阳痿,腰膝酸痛,久咳虚喘,劳嗽咯血",
        "usage": "煎服或研末",
        "dosage": "3-9g",
        "contraindication": "有表邪者慎用",
        "quantity": 50,
        "unit": "g",
        "price": 680,
        "min_stock": 5,
        "notes": ""
    },
    {
        "name": "胡芦巴",
        "alias": "芦巴子、香草",
        "category": "补虚药",
        "nature": "温",
        "taste": "苦",
        "meridian": "归肾经",
        "efficacy": "温肾助阳,散寒止痛",
        "indications": "肾脏虚冷,腹胁胀满,寒湿脚气,寒疝腹痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 250,
        "unit": "g",
        "price": 32,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "韭菜子",
        "alias": "韭子、韭菜仁",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛、甘",
        "meridian": "归肝、肾经",
        "efficacy": "温补肝肾,壮阳固精",
        "indications": "肾虚阳痿,腰膝酸软,遗精遗尿,小便频数",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 300,
        "unit": "g",
        "price": 25,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "阳起石",
        "alias": "羊起石、白石",
        "category": "补虚药",
        "nature": "温",
        "taste": "咸",
        "meridian": "归肾经",
        "efficacy": "温肾壮阳",
        "indications": "肾阳虚衰,阳痿宫冷,腰膝冷痹",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚火旺者忌用,不宜久服",
        "quantity": 150,
        "unit": "g",
        "price": 45,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "紫石英",
        "alias": "萤石、氟石",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归心、肺、肾经",
        "efficacy": "温肾暖宫,镇心安神,温肺平喘",
        "indications": "肾阳不足,宫冷不孕,惊悸怔忡,虚烦不眠,肺寒咳喘",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 200,
        "unit": "g",
        "price": 38,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "海马",
        "alias": "水马、马头鱼",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、咸",
        "meridian": "归肝、肾经",
        "efficacy": "补肾壮阳,调气活血",
        "indications": "肾虚阳痿,遗尿尿频,跌打损伤,疔疮肿毒",
        "usage": "研末冲服",
        "dosage": "1-3g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 80,
        "unit": "g",
        "price": 380,
        "min_stock": 8,
        "notes": ""
    },
    {
        "name": "阿胶",
        "alias": "驴皮胶、傅致胶",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肺、肝、肾经",
        "efficacy": "补血止血,滋阴润燥",
        "indications": "血虚萎黄,眩晕心悸,肌痿无力,吐血衄血,便血崩漏,妊娠胎漏",
        "usage": "烊化兑服",
        "dosage": "3-9g",
        "contraindication": "脾胃虚弱者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 185,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "何首乌",
        "alias": "首乌、赤首乌",
        "category": "补虚药",
        "nature": "微温",
        "taste": "苦、甘、涩",
        "meridian": "归肝、心、肾经",
        "efficacy": "补肝肾,益精血,乌须发,强筋骨",
        "indications": "血虚萎黄,眩晕耳鸣,须发早白,腰膝酸软,肢体麻木,崩漏带下",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "大便溏泄者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 42,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "龙眼肉",
        "alias": "桂圆肉、益智",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归心、脾经",
        "efficacy": "补益心脾,养血安神",
        "indications": "气血不足,心悸怔忡,健忘失眠,血虚萎黄",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "湿盛中满者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 35,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "楮实子",
        "alias": "构树子、谷实",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补肾清肝,明目,利尿",
        "indications": "肝肾不足,腰膝酸软,头晕目昏,水肿胀满",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 250,
        "unit": "g",
        "price": 28,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "北沙参",
        "alias": "海沙参、银沙参",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘、微苦",
        "meridian": "归肺、胃经",
        "efficacy": "养阴清肺,益胃生津",
        "indications": "肺热燥咳,劳嗽咯血,热病伤津,咽干口渴",
        "usage": "煎服",
        "dosage": "5-12g",
        "contraindication": "风寒咳嗽者忌用",
        "quantity": 300,
        "unit": "g",
        "price": 65,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "南沙参",
        "alias": "沙参、泡参",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "养阴清肺,益胃生津,化痰益气",
        "indications": "肺热燥咳,阴虚劳嗽,干咳痰粘,胃阴不足,气虚乏力",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "风寒咳嗽者忌用",
        "quantity": 350,
        "unit": "g",
        "price": 42,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "百合",
        "alias": "白百合、蒜脑薯",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归心、肺经",
        "efficacy": "养阴润肺,清心安神",
        "indications": "阴虚燥咳,劳嗽咯血,虚烦惊悸,失眠多梦,精神恍惚",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "风寒咳嗽者忌用",
        "quantity": 400,
        "unit": "g",
        "price": 38,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "麦冬",
        "alias": "麦门冬、寸冬",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘、微苦",
        "meridian": "归心、肺、胃经",
        "efficacy": "养阴生津,润肺清心",
        "indications": "肺燥干咳,阴虚劳嗽,喉痹咽痛,津伤口渴,内热消渴,心烦失眠",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒泄泻者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 45,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "天冬",
        "alias": "天门冬、明天冬",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归肺、肾经",
        "efficacy": "养阴润燥,清肺生津",
        "indications": "肺燥干咳,顿咳痰黏,咽干口渴,肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒泄泻者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 38,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "石斛",
        "alias": "金钗石斛、吊兰花",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归胃、肾经",
        "efficacy": "益胃生津,滋阴清热",
        "indications": "热病伤津,口干烦渴,胃阴不足,食少干呕,病后虚热不退,阴虚火旺",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "温热病早期阴未伤者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 125,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "玉竹",
        "alias": "萎蕤、女萎",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "养阴润燥,生津止渴",
        "indications": "肺胃阴伤,燥热咳嗽,咽干口渴,内热消渴",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "痰湿气滞者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "黄精",
        "alias": "老虎姜、鸡头参",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺、肾经",
        "efficacy": "补气养阴,健脾润肺,益肾",
        "indications": "脾胃气虚,体倦乏力,胃阴不足,口干食少,肺虚燥咳,劳嗽咯血,精血不足,腰膝酸软",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "痰湿气滞者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 35,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "枸杞子",
        "alias": "杞子、枸杞果",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "滋补肝肾,益精明目",
        "indications": "肝肾不足,腰膝酸软,头晕目昏,视力减退,遗精消渴",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾虚便溏者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 48,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "墨旱莲",
        "alias": "旱莲草、鳢肠",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、酸",
        "meridian": "归肝、肾经",
        "efficacy": "滋补肝肾,凉血止血",
        "indications": "肝肾不足,头晕目眩,须发早白,吐血衄血,尿血血痢,崩漏下血",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "女贞子",
        "alias": "女贞实、冬青子",
        "category": "补虚药",
        "nature": "凉",
        "taste": "甘、苦",
        "meridian": "归肝、肾经",
        "efficacy": "滋补肝肾,明目乌发",
        "indications": "肝肾不足,眩晕耳鸣,腰膝酸软,须发早白,目暗不明",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒泄泻者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "桑椹",
        "alias": "桑果、桑枣",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、酸",
        "meridian": "归心、肝、肾经",
        "efficacy": "滋阴补血,生津润燥",
        "indications": "肝肾不足,血虚精亏,头晕眼花,须发早白,内热消渴,肠燥便秘",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒便溏者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "龟甲",
        "alias": "龟板、下甲",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、咸",
        "meridian": "归肝、肾、心经",
        "efficacy": "滋阴潜阳,益肾强骨,养血补心",
        "indications": "阴虚阳亢,眩晕耳鸣,阴虚火旺,骨蒸潮热,盗汗遗精,肾虚腰痛,筋骨痿软,心虚惊悸",
        "usage": "煎服",
        "dosage": "9-24g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 150,
        "unit": "g",
        "price": 165,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "鳖甲",
        "alias": "甲鱼壳、团鱼甲",
        "category": "补虚药",
        "nature": "寒",
        "taste": "咸",
        "meridian": "归肝、肾经",
        "efficacy": "滋阴潜阳,退热除蒸,软坚散结",
        "indications": "阴虚发热,骨蒸劳热,虚风内动,经闭,癥瘕,久疟疟母",
        "usage": "煎服",
        "dosage": "9-24g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 150,
        "unit": "g",
        "price": 145,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "大黄",
        "alias": "将军、川军",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归脾、胃、大肠、肝、心包经",
        "efficacy": "泻下攻积,清热泻火,凉血解毒,逐瘀通经,利湿退黄",
        "indications": "实热积滞便秘,血热吐衄,目赤咽肿,痈肿疔疮,肠痈腹痛,瘀血经闭,产后瘀阻,跌打损伤,湿热痢疾,黄疸尿赤,淋证,水肿；外治烧烫伤",
        "usage": "煎服",
        "dosage": "3-15g",
        "contraindication": "孕妇及月经期、哺乳期慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 40,
        "notes": "生大黄"
    },
    {
        "name": "芒硝",
        "alias": "马牙硝、盆硝",
        "category": "泻下药",
        "nature": "寒",
        "taste": "咸、苦",
        "meridian": "归胃、大肠经",
        "efficacy": "泻下通便,润燥软坚,清热消肿",
        "indications": "实热便秘,大便燥结,积滞腹痛,肠痈肿痛；外治乳痈,痔疮肿痛",
        "usage": "冲服",
        "dosage": "6-12g",
        "contraindication": "孕妇慎用",
        "quantity": 300,
        "unit": "g",
        "price": 18,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "番泻叶",
        "alias": "泻叶、旃那叶",
        "category": "泻下药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归大肠经",
        "efficacy": "泻热行滞,通便利水",
        "indications": "热结便秘,积滞腹胀",
        "usage": "泡服",
        "dosage": "2-6g",
        "contraindication": "孕妇慎用,用量过大可致恶心呕吐腹痛",
        "quantity": 250,
        "unit": "g",
        "price": 22,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "芦荟",
        "alias": "卢会、讷会",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肝、胃、大肠经",
        "efficacy": "泻下通便,清肝泻火,杀虫疗疳",
        "indications": "热结便秘,惊痫抽搐,小儿疳积,外治癣疮",
        "usage": "入丸散",
        "dosage": "2-5g",
        "contraindication": "孕妇慎用,脾胃虚寒者忌用",
        "quantity": 200,
        "unit": "g",
        "price": 45,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "火麻仁",
        "alias": "麻子仁、大麻仁",
        "category": "泻下药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、胃、大肠经",
        "efficacy": "润肠通便",
        "indications": "血虚津亏,肠燥便秘",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "用量过大可致中毒",
        "quantity": 400,
        "unit": "g",
        "price": 25,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "郁李仁",
        "alias": "李仁、郁子",
        "category": "泻下药",
        "nature": "平",
        "taste": "辛、苦、甘",
        "meridian": "归脾、大肠、小肠经",
        "efficacy": "润燥滑肠,下气利水",
        "indications": "肠燥便秘,水肿腹满,脚气浮肿",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "孕妇慎用",
        "quantity": 300,
        "unit": "g",
        "price": 32,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "松子仁",
        "alias": "松子、海松子",
        "category": "泻下药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归肺、肝、大肠经",
        "efficacy": "润肠通便,润肺止咳",
        "indications": "肠燥便秘,肺燥干咳",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾虚便溏者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "甘遂",
        "alias": "甘泽、苦泽",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、肾、大肠经",
        "efficacy": "泻水逐饮,消肿散结",
        "indications": "水肿胀满,胸腹积水,痰饮积聚,气逆喘咳,二便不利",
        "usage": "入丸散",
        "dosage": "0.5-1g",
        "contraindication": "孕妇忌用,体虚者慎用,反甘草",
        "quantity": 100,
        "unit": "g",
        "price": 85,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "京大戟",
        "alias": "大戟、龙虎草",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、脾、肾经",
        "efficacy": "泻水逐饮,消肿散结",
        "indications": "水肿胀满,胸腹积水,痰饮积聚,瘰疬痰核,痈肿疮毒",
        "usage": "煎服",
        "dosage": "1.5-3g",
        "contraindication": "孕妇忌用,体虚者慎用,反甘草",
        "quantity": 100,
        "unit": "g",
        "price": 65,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "芫花",
        "alias": "赤芫、杜芫",
        "category": "泻下药",
        "nature": "温",
        "taste": "苦、辛",
        "meridian": "归肺、脾、肾经",
        "efficacy": "泻水逐饮,祛痰止咳,杀虫疗疮",
        "indications": "水肿胀满,胸腹积水,痰饮积聚,咳嗽痰喘,头疮白秃,顽癣",
        "usage": "煎服",
        "dosage": "1.5-3g",
        "contraindication": "孕妇忌用,体虚者慎用,反甘草",
        "quantity": 80,
        "unit": "g",
        "price": 55,
        "min_stock": 8,
        "notes": ""
    },
    {
        "name": "商陆",
        "alias": "土人参、山萝卜",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、脾、肾、大肠经",
        "efficacy": "逐水消肿,通利二便,解毒散结",
        "indications": "水肿胀满,二便不利,痈肿疮毒",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "孕妇忌用,脾虚水肿者慎用",
        "quantity": 150,
        "unit": "g",
        "price": 28,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "牵牛子",
        "alias": "二丑、黑白丑",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、肾、大肠经",
        "efficacy": "泻下逐水,去积杀虫",
        "indications": "水肿胀满,二便不利,痰饮积聚,虫积腹痛",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "孕妇忌用,胃弱气虚者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 22,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "巴豆霜",
        "alias": "巴豆、江子",
        "category": "泻下药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归胃、大肠经",
        "efficacy": "峻下冷积,逐水退肿,祛痰利咽,外用蚀疮",
        "indications": "寒积便秘,乳食停滞,腹水臌胀,二便不通,喉风喉痹,痈肿脓成未溃,疥癣恶疮",
        "usage": "入丸散",
        "dosage": "0.1-0.3g",
        "contraindication": "孕妇忌用,体弱者慎用,反牵牛子",
        "quantity": 50,
        "unit": "g",
        "price": 95,
        "min_stock": 5,
        "notes": ""
    },
    {
        "name": "千金子",
        "alias": "续随子、小巴豆",
        "category": "泻下药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肝、肾、大肠经",
        "efficacy": "逐水消肿,破血消癥",
        "indications": "水肿,痰饮,积滞胀满,二便不利,血瘀经闭,癥瘕",
        "usage": "去壳去油用",
        "dosage": "1-2g",
        "contraindication": "孕妇忌用,体弱便溏者慎用",
        "quantity": 80,
        "unit": "g",
        "price": 75,
        "min_stock": 8,
        "notes": ""
    },
    {
        "name": "独活",
        "alias": "独摇草、独滑",
        "category": "祛风湿药",
        "nature": "微温",
        "taste": "辛、苦",
        "meridian": "归肾、膀胱经",
        "efficacy": "祛风除湿,通痹止痛",
        "indications": "风寒湿痹,腰膝疼痛,少阴伏风头痛,风寒挟湿头痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 35,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "威灵仙",
        "alias": "铁脚威灵仙、铁扫帚",
        "category": "祛风湿药",
        "nature": "温",
        "taste": "辛、咸",
        "meridian": "归膀胱经",
        "efficacy": "祛风湿,通经络,消骨鲠",
        "indications": "风湿痹痛,肢体麻木,筋脉拘挛,屈伸不利,骨鲠咽喉",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "气血亏虚者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 28,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "防己",
        "alias": "粉防己、汉防己",
        "category": "祛风湿药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归膀胱、肺经",
        "efficacy": "祛风止痛,利水消肿",
        "indications": "风湿痹痛,水肿脚气,小便不利,湿疹疮毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "胃纳不佳及阴虚体弱者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 38,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "秦艽",
        "alias": "秦胶、秦纠",
        "category": "祛风湿药",
        "nature": "平",
        "taste": "辛、苦",
        "meridian": "归胃、肝、胆经",
        "efficacy": "祛风湿,清虚热,利湿退黄",
        "indications": "风湿痹痛,筋脉拘挛,骨节烦痛,日晡潮热,小儿疳积发热,湿热黄疸",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾虚便溏者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "木瓜",
        "alias": "贴梗海棠、铁脚梨",
        "category": "祛风湿药",
        "nature": "温",
        "taste": "酸",
        "meridian": "归肝、脾经",
        "efficacy": "舒筋活络,和胃化湿",
        "indications": "风湿痹痛,筋脉拘挛,脚气肿痛,吐泻转筋",
        "usage": "煎服",
        "dosage": "6-9g",
        "contraindication": "内有郁热,小便短赤者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 25,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "桑寄生",
        "alias": "寄生、广寄生",
        "category": "祛风湿药",
        "nature": "平",
        "taste": "苦、甘",
        "meridian": "归肝、肾经",
        "efficacy": "祛风湿,补肝肾,强筋骨,安胎元",
        "indications": "风湿痹痛,腰膝酸软,筋骨无力,崩漏经多,妊娠漏血,胎动不安,高血压",
        "usage": "煎服",
        "dosage": "10-20g",
        "contraindication": "无特殊禁忌",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "五加皮",
        "alias": "南五加皮、细柱五加",
        "category": "祛风湿药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归肝、肾经",
        "efficacy": "祛风湿,补肝肾,强筋骨",
        "indications": "风湿痹痛,筋骨痿软,小儿行迟,体虚乏力",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 28,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "蕲蛇",
        "alias": "大白花蛇、五步蛇",
        "category": "祛风湿药",
        "nature": "温",
        "taste": "甘、咸",
        "meridian": "归肝经",
        "efficacy": "祛风通络,止痉止痒",
        "indications": "风湿顽痹,麻木拘挛,中风口眼歪斜,半身不遂,抽搐痉挛,麻风疥癣",
        "usage": "煎服或研末",
        "dosage": "3-9g",
        "contraindication": "血虚生风者慎用",
        "quantity": 100,
        "unit": "g",
        "price": 185,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "乌梢蛇",
        "alias": "乌蛇、黑花蛇",
        "category": "祛风湿药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肝经",
        "efficacy": "祛风通络,止痉止痒",
        "indications": "风湿顽痹,麻木拘挛,中风口眼歪斜,半身不遂,抽搐痉挛,麻风疥癣,瘰疬恶疮",
        "usage": "煎服或研末",
        "dosage": "6-12g",
        "contraindication": "血虚生风者慎用",
        "quantity": 150,
        "unit": "g",
        "price": 125,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "蛇蜕",
        "alias": "蛇皮、龙衣",
        "category": "祛风湿药",
        "nature": "平",
        "taste": "咸、甘",
        "meridian": "归肝经",
        "efficacy": "祛风定惊,退翳解毒",
        "indications": "小儿惊风,抽搐痉挛,翳障,喉痹,疔肿,皮肤瘙痒",
        "usage": "煎服或研末",
        "dosage": "2-3g",
        "contraindication": "孕妇忌用",
        "quantity": 100,
        "unit": "g",
        "price": 65,
        "min_stock": 10,
        "notes": ""
    },
    {
        "name": "苍术",
        "alias": "赤术、青术",
        "category": "化湿药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归脾、胃、肝经",
        "efficacy": "燥湿健脾,祛风散寒,明目",
        "indications": "湿阻中焦,脘腹胀满,泄泻,水肿,脚气痿躄,风湿痹痛,风寒感冒,夜盲",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚内热者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "厚朴",
        "alias": "川朴、紫油厚朴",
        "category": "化湿药",
        "nature": "温",
        "taste": "苦、辛",
        "meridian": "归脾、胃、肺、大肠经",
        "efficacy": "燥湿消痰,下气除满",
        "indications": "湿滞伤中,脘痞吐泻,食积气滞,腹胀便秘,痰饮喘咳",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "孕妇慎用",
        "quantity": 350,
        "unit": "g",
        "price": 35,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "藿香",
        "alias": "广藿香、枝香",
        "category": "化湿药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归脾、胃、肺经",
        "efficacy": "芳香化浊,和中止呕,发表解暑",
        "indications": "湿浊中阻,脘痞呕吐,暑湿表证,湿温初起,发热倦怠,胸闷不舒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 22,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "佩兰",
        "alias": "兰草、水香",
        "category": "化湿药",
        "nature": "平",
        "taste": "辛",
        "meridian": "归脾、胃、肺经",
        "efficacy": "芳香化湿,醒脾开胃,发表解暑",
        "indications": "湿浊中阻,脘痞呕恶,口中甜腻,口臭,多涎,暑湿表证,湿温初起",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 18,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "砂仁",
        "alias": "缩砂仁、阳春砂",
        "category": "化湿药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃、肾经",
        "efficacy": "化湿开胃,温脾止泻,理气安胎",
        "indications": "湿浊中阻,脘痞不饥,脾胃虚寒,呕吐泄泻,妊娠恶阻,胎动不安",
        "usage": "后下",
        "dosage": "3-6g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 85,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "白豆蔻",
        "alias": "豆蔻、圆豆蔻",
        "category": "化湿药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、脾、胃经",
        "efficacy": "化湿行气,温中止呕",
        "indications": "湿浊中阻,不思饮食,湿温初起,胸闷不饥,寒湿呕逆,小儿胃寒吐乳",
        "usage": "后下",
        "dosage": "3-6g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 250,
        "unit": "g",
        "price": 65,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "草豆蔻",
        "alias": "草蔻、偶子",
        "category": "化湿药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃经",
        "efficacy": "燥湿行气,温中止呕",
        "indications": "寒湿内阻,脘腹胀满冷痛,嗳气呕逆,不思饮食",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 45,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "草果",
        "alias": "草果仁、老蔻",
        "category": "化湿药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃经",
        "efficacy": "燥湿温中,除痰截疟",
        "indications": "寒湿内阻,脘腹胀满,痞满呕吐,疟疾寒热,瘟疫发热",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚血燥者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 38,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "泽泻",
        "alias": "水泻、芒芋",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肾、膀胱经",
        "efficacy": "利水渗湿,泄热,化浊降脂",
        "indications": "小便不利,水肿胀满,泄泻尿少,痰饮眩晕,热淋涩痛,高脂血症",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "肾虚精滑者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 25,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "薏苡仁",
        "alias": "薏仁、苡仁",
        "category": "利水渗湿药",
        "nature": "凉",
        "taste": "甘、淡",
        "meridian": "归脾、胃、肺经",
        "efficacy": "利水渗湿,健脾止泻,除痹,排脓,解毒散结",
        "indications": "水肿,脚气,小便不利,脾虚泄泻,湿痹拘挛,肺痈,肠痈,赘疣,癌肿",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "孕妇慎用",
        "quantity": 500,
        "unit": "g",
        "price": 18,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "车前子",
        "alias": "车前实、凤眼前仁",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肝、肾、肺、小肠经",
        "efficacy": "清热利尿通淋,渗湿止泻,明目,祛痰",
        "indications": "热淋涩痛,水肿胀满,暑湿泄泻,目赤肿痛,痰热咳嗽",
        "usage": "包煎",
        "dosage": "9-15g",
        "contraindication": "肾虚精滑者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "滑石",
        "alias": "画石、液石",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "甘、淡",
        "meridian": "归膀胱、肺、胃经",
        "efficacy": "利尿通淋,清热解暑,外用收湿敛疮",
        "indications": "热淋,石淋,尿热涩痛,暑湿烦渴,湿热水泻；外治湿疹,湿疮,痱子",
        "usage": "包煎",
        "dosage": "10-20g",
        "contraindication": "脾虚者慎用,孕妇慎用",
        "quantity": 400,
        "unit": "g",
        "price": 15,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "木通",
        "alias": "关木通、川木通",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、小肠、膀胱经",
        "efficacy": "利尿通淋,清心除烦,通经下乳",
        "indications": "淋证,水肿,心烦尿赤,口舌生疮,经闭乳少,湿热痹痛",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "孕妇慎用,肾功能不全者忌用",
        "quantity": 250,
        "unit": "g",
        "price": 32,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "通草",
        "alias": "大通草、方通草",
        "category": "利水渗湿药",
        "nature": "微寒",
        "taste": "甘、淡",
        "meridian": "归肺、胃经",
        "efficacy": "清热利尿,通气下乳",
        "indications": "湿热尿赤,淋证涩痛,水肿尿少,乳汁不下",
        "usage": "煎服",
        "dosage": "3-5g",
        "contraindication": "孕妇慎用",
        "quantity": 200,
        "unit": "g",
        "price": 35,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "瞿麦",
        "alias": "巨句麦、大菊",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、小肠经",
        "efficacy": "利尿通淋,破血通经",
        "indications": "热淋,血淋,石淋,小便不通,淋沥涩痛,经闭瘀阻",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "孕妇慎用",
        "quantity": 250,
        "unit": "g",
        "price": 22,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "萹蓄",
        "alias": "萹竹、道生草",
        "category": "利水渗湿药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归膀胱经",
        "efficacy": "利尿通淋,杀虫止痒",
        "indications": "热淋涩痛,小便短赤,虫积腹痛,皮肤湿疹,阴痒带下",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾虚者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 18,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "地肤子",
        "alias": "地葵、地麦",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "辛、苦",
        "meridian": "归肾、膀胱经",
        "efficacy": "清热利湿,祛风止痒",
        "indications": "小便涩痛,阴痒带下,风疹,湿疹,皮肤瘙痒",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "阴虚者慎用",
        "quantity": 250,
        "unit": "g",
        "price": 22,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "海金沙",
        "alias": "金沙藤、左转藤",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "甘、咸",
        "meridian": "归膀胱、小肠经",
        "efficacy": "清利湿热,通淋止痛",
        "indications": "热淋,石淋,血淋,膏淋,尿道涩痛",
        "usage": "包煎",
        "dosage": "6-15g",
        "contraindication": "肾阴亏虚者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 38,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "石韦",
        "alias": "石皮、石剑",
        "category": "利水渗湿药",
        "nature": "微寒",
        "taste": "甘、苦",
        "meridian": "归肺、膀胱经",
        "efficacy": "利尿通淋,清肺止咳,凉血止血",
        "indications": "热淋,血淋,石淋,小便不通,淋沥涩痛,肺热咳喘,血热出血",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "阴虚者慎用",
        "quantity": 250,
        "unit": "g",
        "price": 28,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "冬葵子",
        "alias": "葵子、葵菜子",
        "category": "利水渗湿药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归大肠、小肠、膀胱经",
        "efficacy": "利尿通淋,下乳,润肠",
        "indications": "淋证,水肿,乳汁不通,乳房胀痛,肠燥便秘",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "孕妇慎用,脾虚便溏者慎用",
        "quantity": 200,
        "unit": "g",
        "price": 25,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "灯心草",
        "alias": "灯心、灯草",
        "category": "利水渗湿药",
        "nature": "微寒",
        "taste": "甘、淡",
        "meridian": "归心、肺、小肠经",
        "efficacy": "清心火,利小便",
        "indications": "心烦失眠,尿少涩痛,口舌生疮",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "虚寒者慎用",
        "quantity": 150,
        "unit": "g",
        "price": 18,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "附子",
        "alias": "黑顺片、白附片",
        "category": "温里药",
        "nature": "大热",
        "taste": "辛、甘",
        "meridian": "归心、肾、脾经",
        "efficacy": "回阳救逆,补火助阳,散寒止痛",
        "indications": "亡阳虚脱,肢冷脉微,心阳不足,胸痹心痛,虚寒吐泻,脘腹冷痛,肾阳虚衰,阳痿宫冷,阴寒水肿,阳虚外感,寒湿痹痛",
        "usage": "先煎",
        "dosage": "3-15g",
        "contraindication": "孕妇慎用,阴虚阳亢者忌用,反半夏、瓜蒌、贝母、白蔹、白及",
        "quantity": 200,
        "unit": "g",
        "price": 65,
        "min_stock": 20,
        "notes": "制附子"
    },
    {
        "name": "干姜",
        "alias": "白姜、均姜",
        "category": "温里药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归脾、胃、肾、心、肺经",
        "efficacy": "温中散寒,回阳通脉,温肺化饮",
        "indications": "脘腹冷痛,呕吐泄泻,肢冷脉微,寒饮喘咳",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚内热,血热妄行者忌用,孕妇慎用",
        "quantity": 400,
        "unit": "g",
        "price": 22,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "肉桂",
        "alias": "桂皮、牡桂",
        "category": "温里药",
        "nature": "大热",
        "taste": "辛、甘",
        "meridian": "归肾、脾、心、肝经",
        "efficacy": "补火助阳,引火归元,散寒止痛,温通经脉",
        "indications": "阳痿宫冷,腰膝冷痛,肾虚作喘,眩晕目赤,心腹冷痛,虚寒吐泻,寒疝腹痛,痛经经闭",
        "usage": "后下",
        "dosage": "1-5g",
        "contraindication": "阴虚火旺,里有实热,血热妄行者及孕妇忌用",
        "quantity": 250,
        "unit": "g",
        "price": 48,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "吴茱萸",
        "alias": "吴萸、左力",
        "category": "温里药",
        "nature": "热",
        "taste": "辛、苦",
        "meridian": "归肝、脾、胃、肾经",
        "efficacy": "散寒止痛,降逆止呕,助阳止泻",
        "indications": "厥阴头痛,寒疝腹痛,寒湿脚气,经行腹痛,脘腹胀痛,呕吐吞酸,五更泄泻",
        "usage": "煎服",
        "dosage": "2-5g",
        "contraindication": "阴虚有热者忌用,孕妇慎用",
        "quantity": 200,
        "unit": "g",
        "price": 38,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "小茴香",
        "alias": "茴香、香丝菜",
        "category": "温里药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肝、肾、脾、胃经",
        "efficacy": "散寒止痛,理气和胃",
        "indications": "寒疝腹痛,睾丸偏坠,痛经,少腹冷痛,脘腹胀痛,食少吐泻",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚火旺者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 18,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "丁香",
        "alias": "公丁香、丁子香",
        "category": "温里药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃、肺、肾经",
        "efficacy": "温中降逆,补肾助阳",
        "indications": "脾胃虚寒,呃逆呕吐,食少吐泻,心腹冷痛,肾虚阳痿",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "热证及阴虚内热者忌用,畏郁金",
        "quantity": 150,
        "unit": "g",
        "price": 55,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "高良姜",
        "alias": "良姜、小良姜",
        "category": "温里药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归脾、胃经",
        "efficacy": "温胃止呕,散寒止痛",
        "indications": "脘腹冷痛,胃寒呕吐,嗳气吞酸",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚有热者忌用",
        "quantity": 300,
        "unit": "g",
        "price": 28,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "胡椒",
        "alias": "味履支、玉椒",
        "category": "温里药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归胃、大肠经",
        "efficacy": "温中散寒,下气消痰",
        "indications": "胃寒呕吐,腹痛泄泻,食欲不振,癫痫痰多",
        "usage": "研粉冲服",
        "dosage": "0.6-1.5g",
        "contraindication": "阴虚有火者忌用",
        "quantity": 200,
        "unit": "g",
        "price": 35,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "花椒",
        "alias": "川椒、蜀椒",
        "category": "温里药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃、肾经",
        "efficacy": "温中止痛,杀虫止痒",
        "indications": "脘腹冷痛,呕吐泄泻,虫积腹痛,蛔虫症,湿疹瘙痒",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "阴虚火旺者慎用,孕妇慎用",
        "quantity": 350,
        "unit": "g",
        "price": 25,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "荜茇",
        "alias": "荜拨、鼠尾",
        "category": "温里药",
        "nature": "热",
        "taste": "辛",
        "meridian": "归胃、大肠经",
        "efficacy": "温中散寒,下气止痛",
        "indications": "脘腹冷痛,呕吐吞酸,泄泻痢疾,寒疝腹痛,偏头痛",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 150,
        "unit": "g",
        "price": 42,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "荜澄茄",
        "alias": "澄茄、毕澄茄",
        "category": "温里药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归脾、胃、肾、膀胱经",
        "efficacy": "温中散寒,行气止痛",
        "indications": "胃寒呕逆,脘腹冷痛,寒疝腹痛,寒湿郁滞,小便浑浊",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "阴虚火旺者忌用",
        "quantity": 150,
        "unit": "g",
        "price": 38,
        "min_stock": 15,
        "notes": ""
    }
]