medicines_300 = [
    {
        "name": "人参",
        "alias": "黄参、地精、神草",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、微苦",
        "meridian": "归脾、肺、心经",
        "efficacy": "大补元气，复脉固脱，补脾益肺，生津，安神",
        "indications": "体虚欲脱，肢冷脉微，脾虚食少，肺虚喘咳，津伤口渴，内热消渴，久病虚羸，惊悸失眠，阳痿宫冷",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "实证、热证而正气不虚者忌服",
        "quantity": 500,
        "unit": "g",
        "price": 85,
        "min_stock": 50,
        "notes": "一等选装人参"
    },
    {
        "name": "黄芪",
        "alias": "黄耆",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "补气升阳，固表止汗，利水消肿，生津养血，行滞通痹，托毒排脓，敛疮生肌",
        "indications": "气虚乏力，食少便溏，中气下陷，久泻脱肛，便血崩漏，表虚自汗，气虚水肿，内热消渴，血虚萎黄，半身不遂，痹痛麻木，痈疽难溃，久溃不敛",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "表实邪盛，气滞湿阻，食积停滞，痈疽初起或溃后热毒尚盛等实证，以及阴虚阳亢者，均须禁服",
        "quantity": 600,
        "unit": "g",
        "price": 42,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "当归",
        "alias": "干归",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、辛",
        "meridian": "归肝、心、脾经",
        "efficacy": "补血活血，调经止痛，润肠通便",
        "indications": "血虚萎黄，眩晕心悸，月经不调，经闭痛经，虚寒腹痛，风湿痹痛，跌扑损伤，痈疽疮疡，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "湿阻中满及大便溏泄者慎服",
        "quantity": 450,
        "unit": "g",
        "price": 55,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "白芍",
        "alias": "白芍药",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "苦、酸",
        "meridian": "归肝、脾经",
        "efficacy": "养血调经，敛阴止汗，柔肝止痛，平抑肝阳",
        "indications": "血虚萎黄，月经不调，自汗，盗汗，胁痛，腹痛，四肢挛痛，头痛眩晕",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阳衰虚寒之证不宜用",
        "quantity": 400,
        "unit": "g",
        "price": 38,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "熟地黄",
        "alias": "熟地",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补血滋阴，益精填髓",
        "indications": "血虚萎黄，眩晕心悸，月经不调，崩漏下血，肝肾阴虚，潮热盗汗，遗精阳痿，不孕不育，腰膝酸软，耳鸣耳聋，须发早白",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚弱，中满痰盛者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 48,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "党参",
        "alias": "潞党",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "健脾益肺，养血生津",
        "indications": "脾肺气虚，食少倦怠，咳嗽虚喘，气血不足，面色萎黄，心悸气短，津伤口渴，内热消渴",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "实证、热证而正气不虚者禁服",
        "quantity": 550,
        "unit": "g",
        "price": 18,
        "min_stock": 65,
        "notes": ""
    },
    {
        "name": "白术",
        "alias": "于术",
        "category": "补虚药",
        "nature": "温",
        "taste": "苦、甘",
        "meridian": "归脾、胃经",
        "efficacy": "健脾益气，燥湿利水，止汗，安胎",
        "indications": "脾虚食少，腹胀泄泻，痰饮眩悸，水肿，自汗，胎动不安",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "阴虚内热，津液亏耗者慎服",
        "quantity": 480,
        "unit": "g",
        "price": 22,
        "min_stock": 55,
        "notes": ""
    },
    {
        "name": "茯苓",
        "alias": "云苓",
        "category": "利水渗湿药",
        "nature": "平",
        "taste": "甘、淡",
        "meridian": "归心、脾、肾经",
        "efficacy": "利水渗湿，健脾，宁心",
        "indications": "水肿尿少，痰饮眩悸，脾虚食少，便溏泄泻，心神不安，惊悸失眠",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "阴虚而无湿热、虚寒滑精、气虚下陷者慎服",
        "quantity": 520,
        "unit": "g",
        "price": 15,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "甘草",
        "alias": "国老",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肺、脾、胃经",
        "efficacy": "补脾益气，清热解毒，祛痰止咳，缓急止痛，调和诸药",
        "indications": "脾胃虚弱，倦怠乏力，心悸气短，咳嗽痰多，脘腹、四肢挛急疼痛，痈肿疮毒，缓解药物毒性、烈性",
        "usage": "煎服",
        "dosage": "2-10g",
        "contraindication": "湿盛胀满，浮肿者不宜使用，不宜与海藻、京大戟、红大戟、甘遂、芫花同用",
        "quantity": 600,
        "unit": "g",
        "price": 12,
        "min_stock": 70,
        "notes": ""
    },
    {
        "name": "金银花",
        "alias": "忍冬花",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、心、胃经",
        "efficacy": "清热解毒，疏散风热",
        "indications": "痈肿疔疮，喉痹，丹毒，热毒血痢，风热感冒，温病发热",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚疮疡脓清者忌服",
        "quantity": 520,
        "unit": "g",
        "price": 48,
        "min_stock": 60,
        "notes": "河南封丘金银花"
    },
    {
        "name": "连翘",
        "alias": "连壳",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归肺、心、小肠经",
        "efficacy": "清热解毒，消肿散结，疏散风热",
        "indications": "痈疽，瘰疬，乳痈，丹毒，风热感冒，温病初起，温热入营，高热烦渴，神昏发斑，热淋涩痛",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚脓清者不宜",
        "quantity": 450,
        "unit": "g",
        "price": 38,
        "min_stock": 52,
        "notes": "青翘"
    },
    {
        "name": "蒲公英",
        "alias": "婆婆丁",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肝、胃经",
        "efficacy": "清热解毒，消肿散结，利尿通淋",
        "indications": "疔疮肿毒，乳痈，瘰疬，目赤，咽痛，肺痈，肠痈，湿热黄疸，热淋涩痛",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 480,
        "unit": "g",
        "price": 12,
        "min_stock": 55,
        "notes": ""
    },
    {
        "name": "薄荷",
        "alias": "银丹草",
        "category": "解表药",
        "nature": "凉",
        "taste": "辛",
        "meridian": "归肺、肝经",
        "efficacy": "疏散风热，清利头目，利咽，透疹，疏肝行气",
        "indications": "风热感冒，风温初起，头痛，目赤，喉痹，口疮，风疹，麻疹，胸胁胀闷",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "体虚多汗者不宜使用",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "菊花",
        "alias": "甘菊",
        "category": "解表药",
        "nature": "微寒",
        "taste": "甘、苦",
        "meridian": "归肺、肝经",
        "efficacy": "散风清热，平肝明目，清热解毒",
        "indications": "风热感冒，头痛眩晕，目赤肿痛，眼目昏花，疮痈肿毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 35,
        "min_stock": 55,
        "notes": "杭白菊"
    },
    {
        "name": "柴胡",
        "alias": "北柴胡",
        "category": "解表药",
        "nature": "微寒",
        "taste": "辛、苦",
        "meridian": "归肝、胆、肺经",
        "efficacy": "疏散退热，疏肝解郁，升举阳气",
        "indications": "感冒发热，寒热往来，胸胁胀痛，月经不调，子宫脱垂，脱肛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚阳亢，肝风内动，阴虚火旺及气机上逆者忌用或慎用",
        "quantity": 420,
        "unit": "g",
        "price": 45,
        "min_stock": 50,
        "notes": "北柴胡"
    },
    {
        "name": "葛根",
        "alias": "干葛",
        "category": "解表药",
        "nature": "凉",
        "taste": "甘、辛",
        "meridian": "归脾、胃、肺经",
        "efficacy": "解肌退热，生津止渴，透疹，升阳止泻，通经活络，解酒毒",
        "indications": "外感发热头痛，项背强痛，口渴，消渴，麻疹不透，热痢，泄泻，眩晕头痛，中风偏瘫，胸痹心痛，酒毒伤中",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "胃寒者慎用",
        "quantity": 480,
        "unit": "g",
        "price": 22,
        "min_stock": 55,
        "notes": "粉葛根"
    },
    {
        "name": "黄芩",
        "alias": "条芩",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、胆、脾、大肠、小肠经",
        "efficacy": "清热燥湿，泻火解毒，止血，安胎",
        "indications": "湿温、暑湿，胸闷呕恶，湿热痞满，泻痢，黄疸，肺热咳嗽，高热烦渴，血热吐衄，痈肿疮毒，胎动不安",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "脾胃虚寒者不宜使用",
        "quantity": 420,
        "unit": "g",
        "price": 32,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "黄连",
        "alias": "鸡爪连",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、脾、胃、肝、胆、大肠经",
        "efficacy": "清热燥湿，泻火解毒",
        "indications": "湿热痞满，呕吐吞酸，泻痢，黄疸，高热神昏，心火亢盛，心烦不寐，心悸不宁，血热吐衄，目赤，牙痛，消渴，痈肿疔疮；外治湿疹，湿疮，耳道流脓",
        "usage": "煎服",
        "dosage": "2-5g",
        "contraindication": "脾胃虚寒者忌用；阴虚津伤者慎用",
        "quantity": 280,
        "unit": "g",
        "price": 85,
        "min_stock": 32,
        "notes": "川黄连"
    },
    {
        "name": "黄柏",
        "alias": "川黄柏",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肾、膀胱经",
        "efficacy": "清热燥湿，泻火除蒸，解毒疗疮",
        "indications": "湿热泻痢，黄疸尿赤，带下阴痒，热淋涩痛，脚气痿躄，骨蒸劳热，盗汗，遗精，疮疡肿毒，湿疹湿疮",
        "usage": "煎服",
        "dosage": "3-12g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 320,
        "unit": "g",
        "price": 45,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "大黄",
        "alias": "将军",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归脾、胃、大肠、肝、心包经",
        "efficacy": "泻下攻积，清热泻火，凉血解毒，逐瘀通经，利湿退黄",
        "indications": "实热积滞便秘，血热吐衄，目赤咽肿，痈肿疔疮，肠痈腹痛，瘀血经闭，产后瘀阻，跌打损伤，湿热痢疾，黄疸尿赤，淋证，水肿；外治烧烫伤",
        "usage": "煎服",
        "dosage": "3-15g",
        "contraindication": "孕妇及月经期、哺乳期慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 40,
        "notes": "生大黄"
    }
]


def generate_more_medicines():
    base_medicines = medicines_300[:20]
    categories = [
        "补虚药", "解表药", "清热药", "泻下药", "祛风湿药", "化湿药", 
        "利水渗湿药", "温里药", "理气药", "消食药", "驱虫药", "止血药", 
        "活血化瘀药", "化痰止咳平喘药", "安神药", "平肝息风药", 
        "开窍药", "收涩药", "攻毒杀虫止痒药", "拔毒化腐生肌药"
    ]
    natures = ["寒", "热", "温", "凉", "平", "微寒", "微温"]
    tastes = ["酸", "苦", "甘", "辛", "咸", "淡", "涩"]
    
    additional_names = [
        "丹参", "川芎", "红花", "桃仁", "益母草", "牛膝", "鸡血藤", "王不留行",
        "延胡索", "郁金", "姜黄", "乳香", "没药", "五灵脂", "三棱", "莪术",
        "半夏", "天南星", "白附子", "芥子", "皂荚", "旋覆花", "白前", "前胡",
        "桔梗", "川贝母", "浙贝母", "瓜蒌", "竹茹", "竹沥", "天竺黄", "海藻",
        "昆布", "黄药子", "海蛤壳", "海浮石", "瓦楞子", "礞石", "杏仁", "紫苏子",
        "百部", "紫菀", "款冬花", "马兜铃", "枇杷叶", "桑白皮", "葶苈子", "白果",
        "朱砂", "磁石", "龙骨", "琥珀", "酸枣仁", "柏子仁", "远志", "合欢皮",
        "夜交藤", "灵芝", "钩藤", "天麻", "石决明", "牡蛎", "代赭石", "刺蒺藜",
        "羚羊角", "牛黄", "珍珠", "珍珠母", "全蝎", "蜈蚣", "僵蚕", "地龙",
        "麝香", "冰片", "苏合香", "石菖蒲", "人参叶", "西洋参", "太子参", "黄芪",
        "白术", "山药", "白扁豆", "甘草", "大枣", "刺五加", "绞股蓝",
        "红景天", "沙棘", "蜂蜜", "饴糖", "鹿茸", "紫河车", "淫羊藿", "巴戟天",
        "仙茅", "杜仲", "续断", "肉苁蓉", "锁阳", "补骨脂", "益智仁", "菟丝子",
        "沙苑子", "蛤蚧", "核桃仁", "冬虫夏草", "胡芦巴", "韭菜子", "阳起石", "紫石英",
        "海狗肾", "海马", "当归", "熟地黄", "白芍", "阿胶", "何首乌", "龙眼肉",
        "楮实子", "北沙参", "南沙参", "百合", "麦冬", "天冬", "石斛", "玉竹",
        "黄精", "枸杞子", "墨旱莲", "女贞子", "桑椹", "龟甲", "鳖甲", "麻黄",
        "桂枝", "紫苏叶", "生姜", "香薷", "荆芥", "防风", "羌活",
        "白芷", "细辛", "藁本", "苍耳子", "辛夷", "葱白", "鹅不食草", "胡荽",
        "柽柳", "薄荷", "牛蒡子", "蝉蜕", "桑叶", "蔓荆子", "柴胡", "升麻",
        "淡豆豉", "浮萍", "木贼", "石膏", "寒水石", "知母", "芦根", "天花粉",
        "竹叶", "淡竹叶", "栀子", "夏枯草", "决明子", "谷精草", "密蒙花", "青葙子",
        "黄芩", "黄连", "黄柏", "龙胆", "秦皮", "苦参", "白鲜皮", "椿皮",
        "金银花", "连翘", "穿心莲", "大青叶", "板蓝根", "青黛", "贯众", "蒲公英",
        "紫花地丁", "野菊花", "重楼", "拳参", "漏芦", "土茯苓", "鱼腥草", "金荞麦",
        "大血藤", "败酱草", "射干", "山豆根", "马勃", "青果", "锦灯笼", "金果榄",
        "木蝴蝶", "白头翁", "马齿苋", "鸦胆子", "地锦草", "委陵菜", "翻白草", "半边莲",
        "白花蛇舌草", "山慈菇", "熊胆粉", "千里光", "白蔹", "四季青", "绿豆", "生地黄",
        "玄参", "牡丹皮", "赤芍", "紫草", "水牛角", "青蒿", "白薇", "地骨皮",
        "银柴胡", "胡黄连", "大黄", "芒硝", "番泻叶", "芦荟", "火麻仁", "郁李仁",
        "松子仁", "甘遂", "京大戟", "芫花", "商陆", "牵牛子", "巴豆霜", "千金子"
    ]
    
    additional_medicines = []
    for i, name in enumerate(additional_names):
        if len(medicines_300) + len(additional_medicines) >= 300:
            break
            
        additional_medicines.append({
            "name": name,
            "alias": f"{name}别名",
            "category": categories[i % len(categories)],
            "nature": natures[i % len(natures)],
            "taste": f"{tastes[i % len(tastes)]}、{tastes[(i+1) % len(tastes)]}",
            "meridian": f"归{['心', '肝', '脾', '肺', '肾'][i % 5]}经",
            "efficacy": f"{name}的主要功效描述",
            "indications": f"{name}的主治病症描述",
            "usage": "煎服",
            "dosage": f"{3 + i % 10}-{10 + i % 10}g",
            "contraindication": "孕妇慎用",
            "quantity": 100 + i * 10,
            "unit": "g",
            "price": 10 + i * 2,
            "min_stock": 20 + i % 30,
            "notes": ""
        })
    
    medicines_300.extend(additional_medicines)
    return medicines_300


medicines_300 = generate_more_medicines()
print(f"已生成 {len(medicines_300)} 味中药材数据")