
medicines_300 = [
    {
        "name": "人参",
        "alias": "黄参、地精、神草",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、微苦",
        "meridian": "归脾、肺、心经",
        "efficacy": "大补元气，复脉固脱，补脾益肺，生津，安神",
        "indications": "体虚欲脱，肢冷脉微，脾虚食少，肺虚喘咳，津伤口渴，内热消渴，久病虚羸，惊悸失眠，阳痿宫冷",
        "usage": "煎服",
        "dosage": "3-9g；挽救虚脱可用15-30g",
        "contraindication": "实证、热证而正气不虚者忌服",
        "quantity": 500,
        "unit": "g",
        "price": 85,
        "min_stock": 50,
        "notes": "一等选装人参"
    },
    {
        "name": "黄芪",
        "alias": "黄耆",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "补气升阳，固表止汗，利水消肿，生津养血，行滞通痹，托毒排脓，敛疮生肌",
        "indications": "气虚乏力，食少便溏，中气下陷，久泻脱肛，便血崩漏，表虚自汗，气虚水肿，内热消渴，血虚萎黄，半身不遂，痹痛麻木，痈疽难溃，久溃不敛",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "表实邪盛，气滞湿阻，食积停滞，痈疽初起或溃后热毒尚盛等实证，以及阴虚阳亢者，均须禁服",
        "quantity": 600,
        "unit": "g",
        "price": 42,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "当归",
        "alias": "干归",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘、辛",
        "meridian": "归肝、心、脾经",
        "efficacy": "补血活血，调经止痛，润肠通便",
        "indications": "血虚萎黄，眩晕心悸，月经不调，经闭痛经，虚寒腹痛，风湿痹痛，跌扑损伤，痈疽疮疡，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "湿阻中满及大便溏泄者慎服",
        "quantity": 450,
        "unit": "g",
        "price": 55,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "白芍",
        "alias": "白芍药",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "苦、酸",
        "meridian": "归肝、脾经",
        "efficacy": "养血调经，敛阴止汗，柔肝止痛，平抑肝阳",
        "indications": "血虚萎黄，月经不调，自汗，盗汗，胁痛，腹痛，四肢挛痛，头痛眩晕",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阳衰虚寒之证不宜用",
        "quantity": 400,
        "unit": "g",
        "price": 38,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "熟地黄",
        "alias": "熟地",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "补血滋阴，益精填髓",
        "indications": "血虚萎黄，眩晕心悸，月经不调，崩漏下血，肝肾阴虚，潮热盗汗，遗精阳痿，不孕不育，腰膝酸软，耳鸣耳聋，须发早白",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚弱，中满痰盛者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 48,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "党参",
        "alias": "潞党",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺经",
        "efficacy": "健脾益肺，养血生津",
        "indications": "脾肺气虚，食少倦怠，咳嗽虚喘，气血不足，面色萎黄，心悸气短，津伤口渴，内热消渴",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "实证、热证而正气不虚者禁服",
        "quantity": 550,
        "unit": "g",
        "price": 18,
        "min_stock": 65,
        "notes": ""
    },
    {
        "name": "白术",
        "alias": "于术",
        "category": "补虚药",
        "nature": "温",
        "taste": "苦、甘",
        "meridian": "归脾、胃经",
        "efficacy": "健脾益气，燥湿利水，止汗，安胎",
        "indications": "脾虚食少，腹胀泄泻，痰饮眩悸，水肿，自汗，胎动不安",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "阴虚内热，津液亏耗者慎服",
        "quantity": 480,
        "unit": "g",
        "price": 22,
        "min_stock": 55,
        "notes": ""
    },
    {
        "name": "茯苓",
        "alias": "云苓",
        "category": "利水渗湿药",
        "nature": "平",
        "taste": "甘、淡",
        "meridian": "归心、脾、肾经",
        "efficacy": "利水渗湿，健脾，宁心",
        "indications": "水肿尿少，痰饮眩悸，脾虚食少，便溏泄泻，心神不安，惊悸失眠",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "阴虚而无湿热、虚寒滑精、气虚下陷者慎服",
        "quantity": 520,
        "unit": "g",
        "price": 15,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "甘草",
        "alias": "国老",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归心、肺、脾、胃经",
        "efficacy": "补脾益气，清热解毒，祛痰止咳，缓急止痛，调和诸药",
        "indications": "脾胃虚弱，倦怠乏力，心悸气短，咳嗽痰多，脘腹、四肢挛急疼痛，痈肿疮毒，缓解药物毒性、烈性",
        "usage": "煎服",
        "dosage": "2-10g",
        "contraindication": "湿盛胀满，浮肿者不宜使用，不宜与海藻、京大戟、红大戟、甘遂、芫花同用",
        "quantity": 600,
        "unit": "g",
        "price": 12,
        "min_stock": 70,
        "notes": ""
    },
    {
        "name": "西洋参",
        "alias": "花旗参",
        "category": "补虚药",
        "nature": "凉",
        "taste": "甘、微苦",
        "meridian": "归心、肺、肾经",
        "efficacy": "补气养阴，清热生津",
        "indications": "气虚阴亏，虚热烦倦，咳喘痰血，内热消渴，口燥咽干",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "中阳衰微，胃有寒湿者忌服",
        "quantity": 200,
        "unit": "g",
        "price": 180,
        "min_stock": 30,
        "notes": "进口西洋参"
    },
    {
        "name": "太子参",
        "alias": "孩儿参",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘、微苦",
        "meridian": "归脾、肺经",
        "efficacy": "益气健脾，生津润肺",
        "indications": "脾虚体倦，食欲不振，病后虚弱，气阴不足，自汗口渴，肺燥干咳",
        "usage": "煎服",
        "dosage": "9-30g",
        "contraindication": "邪实而正气不虚者慎用",
        "quantity": 350,
        "unit": "g",
        "price": 45,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "山药",
        "alias": "薯蓣",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺、肾经",
        "efficacy": "健脾养胃，生津益肺，补肾涩精",
        "indications": "脾虚食少，久泻不止，肺虚喘咳，肾虚遗精，带下，尿频，虚热消渴",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "湿盛中满或有实邪、积滞者禁服",
        "quantity": 400,
        "unit": "g",
        "price": 25,
        "min_stock": 45,
        "notes": "怀山药"
    },
    {
        "name": "白扁豆",
        "alias": "藊豆",
        "category": "补虚药",
        "nature": "微温",
        "taste": "甘",
        "meridian": "归脾、胃经",
        "efficacy": "健脾化湿，和中消暑",
        "indications": "脾胃虚弱，食欲不振，大便溏泻，白带过多，暑湿吐泻，胸闷腹胀",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "多食壅气，伤寒邪炽者禁用",
        "quantity": 300,
        "unit": "g",
        "price": 18,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "大枣",
        "alias": "红枣",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归脾、胃、心经",
        "efficacy": "补中益气，养血安神",
        "indications": "脾虚食少，乏力便溏，妇人脏躁",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "凡湿盛、痰凝、食滞、虫积及齿病者，慎服或禁服",
        "quantity": 800,
        "unit": "g",
        "price": 15,
        "min_stock": 100,
        "notes": "优质红枣"
    },
    {
        "name": "蜂蜜",
        "alias": "白蜜",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肺、脾、大肠经",
        "efficacy": "补中，润燥，止痛，解毒；外用生肌敛疮",
        "indications": "脘腹虚痛，肺燥干咳，肠燥便秘，解乌头类药毒；外治疮疡不敛，水火烫伤",
        "usage": "煎服或冲服",
        "dosage": "15-30g",
        "contraindication": "湿热痰滞，胸闷不宽及便溏或泄泻者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 35,
        "notes": "百花蜂蜜"
    },
    {
        "name": "饴糖",
        "alias": "麦芽糖",
        "category": "补虚药",
        "nature": "温",
        "taste": "甘",
        "meridian": "归脾、胃、肺经",
        "efficacy": "补中缓急，润肺止咳，解毒",
        "indications": "脾胃虚寒，里急腹痛，肺燥咳嗽，咽痛，吐血，口渴，咽痛，便秘",
        "usage": "烊化冲服",
        "dosage": "15-20g",
        "contraindication": "湿热内郁，中满吐逆者忌服",
        "quantity": 200,
        "unit": "g",
        "price": 28,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "红景天",
        "alias": "扫罗玛尔布",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归肺、心经",
        "efficacy": "益气活血，通脉平喘",
        "indications": "气虚血瘀，胸痹心痛，中风偏瘫，倦怠气喘",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "儿童、孕妇慎用",
        "quantity": 250,
        "unit": "g",
        "price": 65,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "刺五加",
        "alias": "五加皮",
        "category": "补虚药",
        "nature": "温",
        "taste": "辛、微苦",
        "meridian": "归脾、肾、心经",
        "efficacy": "益气健脾，补肾安神",
        "indications": "脾肾阳虚，体虚乏力，食欲不振，腰膝酸痛，失眠多梦",
        "usage": "煎服",
        "dosage": "9-27g",
        "contraindication": "阴虚火旺者慎服",
        "quantity": 280,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "绞股蓝",
        "alias": "七叶胆",
        "category": "补虚药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肺、脾、肾经",
        "efficacy": "益气健脾，化痰止咳，清热解毒",
        "indications": "脾虚乏力，虚劳失精，白细胞减少症，高脂血症，病毒性肝炎，慢性胃肠炎，慢性气管炎",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "虚寒证忌用",
        "quantity": 320,
        "unit": "g",
        "price": 25,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "沙棘",
        "alias": "醋柳果",
        "category": "补虚药",
        "nature": "温",
        "taste": "酸、涩",
        "meridian": "归脾、胃、肺、心经",
        "efficacy": "健脾消食，止咳祛痰，活血散瘀",
        "indications": "脾虚食少，食积腹痛，咳嗽痰多，胸痹心痛，瘀血经闭，跌扑瘀肿",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "胃酸过多者慎服",
        "quantity": 200,
        "unit": "g",
        "price": 48,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "麻黄",
        "alias": "龙沙",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、微苦",
        "meridian": "归肺、膀胱经",
        "efficacy": "发汗解表，宣肺平喘，利水消肿",
        "indications": "风寒感冒，胸闷喘咳，风水浮肿；蜜麻黄润肺止咳，多用于表证已解，气喘咳嗽",
        "usage": "煎服",
        "dosage": "2-10g",
        "contraindication": "凡表虚自汗、阴虚盗汗及虚喘者均当忌用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "桂枝",
        "alias": "柳桂",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、甘",
        "meridian": "归心、肺、膀胱经",
        "efficacy": "发汗解肌，温通经脉，助阳化气，平冲降气",
        "indications": "风寒感冒，脘腹冷痛，血寒经闭，关节痹痛，痰饮，水肿，心悸，奔豚",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "凡外感热病、阴虚火旺、血热妄行等证，均当忌用；孕妇及月经过多者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 22,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "紫苏叶",
        "alias": "苏叶",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、脾经",
        "efficacy": "解表散寒，行气和胃",
        "indications": "风寒感冒，咳嗽呕恶，妊娠呕吐，鱼蟹中毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚、气虚及温病者慎服",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "生姜",
        "alias": "鲜生姜",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、脾、胃经",
        "efficacy": "解表散寒，温中止呕，化痰止咳，解鱼蟹毒",
        "indications": "风寒感冒，胃寒呕吐，寒痰咳嗽，鱼蟹中毒",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "热盛及阴虚内热者忌服",
        "quantity": 600,
        "unit": "g",
        "price": 8,
        "min_stock": 70,
        "notes": ""
    },
    {
        "name": "香薷",
        "alias": "香茹",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "发汗解表，化湿和中，利水消肿",
        "indications": "暑湿感冒，恶寒发热，头痛无汗，腹痛吐泻，水肿，小便不利",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "表虚有汗及暑热证当忌用",
        "quantity": 280,
        "unit": "g",
        "price": 25,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "荆芥",
        "alias": "假苏",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、肝经",
        "efficacy": "解表散风，透疹，消疮",
        "indications": "感冒，头痛，麻疹，风疹，疮疡初起；炒炭治便血，崩漏，产后血晕",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "表虚自汗、阴虚头痛忌用",
        "quantity": 420,
        "unit": "g",
        "price": 20,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "防风",
        "alias": "铜芸",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛、甘",
        "meridian": "归膀胱、肝、脾经",
        "efficacy": "祛风解表，胜湿止痛，止痉",
        "indications": "感冒头痛，风湿痹痛，风疹瘙痒，破伤风",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴血亏虚、热病动风者不宜使用",
        "quantity": 380,
        "unit": "g",
        "price": 35,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "羌活",
        "alias": "羌青",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归膀胱、肾经",
        "efficacy": "解表散寒，祛风除湿，止痛",
        "indications": "风寒感冒，头痛项强，风湿痹痛，肩背酸痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "血虚痹痛者忌用；阴虚头痛者慎用",
        "quantity": 320,
        "unit": "g",
        "price": 42,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "白芷",
        "alias": "香白芷",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归胃、大肠、肺经",
        "efficacy": "解表散寒，祛风止痛，宣通鼻窍，燥湿止带，消肿排脓",
        "indications": "感冒头痛，眉棱骨痛，鼻塞流涕，鼻鼽，鼻渊，牙痛，带下，疮疡肿痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚血热者忌服",
        "quantity": 360,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "细辛",
        "alias": "小辛",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归心、肺、肾经",
        "efficacy": "解表散寒，祛风止痛，通窍，温肺化饮",
        "indications": "风寒感冒，头痛，牙痛，鼻塞流涕，鼻鼽，鼻渊，风湿痹痛，痰饮喘咳",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "阴虚阳亢头痛、肺燥伤阴干咳者忌用；不宜与藜芦同用",
        "quantity": 180,
        "unit": "g",
        "price": 55,
        "min_stock": 20,
        "notes": "辽细辛"
    },
    {
        "name": "藁本",
        "alias": "藁茇",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归膀胱经",
        "efficacy": "祛风散寒，除湿止痛",
        "indications": "风寒感冒，巅顶疼痛，风湿痹痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴血亏虚、肝阳上亢、火热内盛之头痛者忌服",
        "quantity": 250,
        "unit": "g",
        "price": 38,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "苍耳子",
        "alias": "老苍子",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归肺经",
        "efficacy": "散风寒，通鼻窍，祛风湿",
        "indications": "风寒头痛，鼻塞流涕，鼻鼽，鼻渊，风疹瘙痒，湿痹拘挛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "血虚头痛不宜服用；过量服用易致中毒",
        "quantity": 280,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "辛夷",
        "alias": "木笔花",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "散风寒，通鼻窍",
        "indications": "风寒头痛，鼻塞流涕，鼻鼽，鼻渊",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "鼻病因于阴虚火旺者忌服",
        "quantity": 220,
        "unit": "g",
        "price": 45,
        "min_stock": 28,
        "notes": ""
    },
    {
        "name": "葱白",
        "alias": "葱茎白",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "发汗解表，散寒通阳",
        "indications": "风寒感冒，阴盛格阳",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "表虚多汗者忌服",
        "quantity": 300,
        "unit": "g",
        "price": 12,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "薄荷",
        "alias": "银丹草",
        "category": "解表药",
        "nature": "凉",
        "taste": "辛",
        "meridian": "归肺、肝经",
        "efficacy": "疏散风热，清利头目，利咽，透疹，疏肝行气",
        "indications": "风热感冒，风温初起，头痛，目赤，喉痹，口疮，风疹，麻疹，胸胁胀闷",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "体虚多汗者不宜使用",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "牛蒡子",
        "alias": "大力子",
        "category": "解表药",
        "nature": "寒",
        "taste": "辛、苦",
        "meridian": "归肺、胃经",
        "efficacy": "疏散风热，宣肺透疹，解毒利咽",
        "indications": "风热感冒，咳嗽痰多，麻疹，风疹，咽喉肿痛，痄腮，丹毒，痈肿疮毒",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "气虚便溏者慎用",
        "quantity": 320,
        "unit": "g",
        "price": 25,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "蝉蜕",
        "alias": "蝉衣",
        "category": "解表药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、肝经",
        "efficacy": "疏散风热，利咽，透疹，明目退翳，解痉",
        "indications": "风热感冒，咽痛音哑，麻疹不透，风疹瘙痒，目赤翳障，惊风抽搐，破伤风",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "孕妇慎用",
        "quantity": 280,
        "unit": "g",
        "price": 65,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "桑叶",
        "alias": "家桑",
        "category": "解表药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归肺、肝经",
        "efficacy": "疏散风热，清肺润燥，清肝明目",
        "indications": "风热感冒，肺热燥咳，头晕头痛，目赤昏花",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾胃虚寒者慎服",
        "quantity": 400,
        "unit": "g",
        "price": 15,
        "min_stock": 48,
        "notes": "霜桑叶"
    },
    {
        "name": "菊花",
        "alias": "甘菊",
        "category": "解表药",
        "nature": "微寒",
        "taste": "甘、苦",
        "meridian": "归肺、肝经",
        "efficacy": "散风清热，平肝明目，清热解毒",
        "indications": "风热感冒，头痛眩晕，目赤肿痛，眼目昏花，疮痈肿毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 450,
        "unit": "g",
        "price": 35,
        "min_stock": 55,
        "notes": "杭白菊"
    },
    {
        "name": "蔓荆子",
        "alias": "万荆子",
        "category": "解表药",
        "nature": "微寒",
        "taste": "辛、苦",
        "meridian": "归膀胱、肝、胃经",
        "efficacy": "疏散风热，清利头目",
        "indications": "风热感冒头痛，齿龈肿痛，目赤多泪，目暗不明，头晕目眩",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "血虚有火之头痛目眩及胃虚者慎服",
        "quantity": 260,
        "unit": "g",
        "price": 38,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "柴胡",
        "alias": "北柴胡",
        "category": "解表药",
        "nature": "微寒",
        "taste": "辛、苦",
        "meridian": "归肝、胆、肺经",
        "efficacy": "疏散退热，疏肝解郁，升举阳气",
        "indications": "感冒发热，寒热往来，胸胁胀痛，月经不调，子宫脱垂，脱肛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚阳亢，肝风内动，阴虚火旺及气机上逆者忌用或慎用",
        "quantity": 420,
        "unit": "g",
        "price": 45,
        "min_stock": 50,
        "notes": "北柴胡"
    },
    {
        "name": "升麻",
        "alias": "周升麻",
        "category": "解表药",
        "nature": "微寒",
        "taste": "辛、微甘",
        "meridian": "归肺、脾、胃、大肠经",
        "efficacy": "发表透疹，清热解毒，升举阳气",
        "indications": "风热头痛，齿痛，口疮，咽喉肿痛，麻疹不透，阳毒发斑，脱肛，子宫脱垂",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "麻疹已透，阴虚火旺，以及阴虚阳亢者，均当忌用",
        "quantity": 300,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "葛根",
        "alias": "干葛",
        "category": "解表药",
        "nature": "凉",
        "taste": "甘、辛",
        "meridian": "归脾、胃、肺经",
        "efficacy": "解肌退热，生津止渴，透疹，升阳止泻，通经活络，解酒毒",
        "indications": "外感发热头痛，项背强痛，口渴，消渴，麻疹不透，热痢，泄泻，眩晕头痛，中风偏瘫，胸痹心痛，酒毒伤中",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "胃寒者慎用",
        "quantity": 480,
        "unit": "g",
        "price": 22,
        "min_stock": 55,
        "notes": "粉葛根"
    },
    {
        "name": "石膏",
        "alias": "细石",
        "category": "清热药",
        "nature": "大寒",
        "taste": "甘、辛",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，除烦止渴",
        "indications": "外感热病，高热烦渴，肺热喘咳，胃火亢盛，头痛，牙痛",
        "usage": "煎服",
        "dosage": "15-60g",
        "contraindication": "脾胃虚寒及血虚、阴虚发热者忌用",
        "quantity": 520,
        "unit": "g",
        "price": 8,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "知母",
        "alias": "连母",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肺、胃、肾经",
        "efficacy": "清热泻火，滋阴润燥",
        "indications": "外感热病，高热烦渴，肺热燥咳，骨蒸潮热，内热消渴，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒，大便溏泄者忌服",
        "quantity": 380,
        "unit": "g",
        "price": 28,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "芦根",
        "alias": "苇茎",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，生津止渴，除烦，止呕，利尿",
        "indications": "热病烦渴，肺热咳嗽，肺痈吐脓，胃热呕哕，热淋涩痛",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "脾胃虚寒者忌服",
        "quantity": 420,
        "unit": "g",
        "price": 15,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "天花粉",
        "alias": "瓜蒌根",
        "category": "清热药",
        "nature": "微寒",
        "taste": "甘、微苦",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，生津止渴，消肿排脓",
        "indications": "热病烦渴，肺热燥咳，内热消渴，疮疡肿毒",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚寒，大便溏泄者忌服；不宜与川乌、制川乌、草乌、制草乌、附子同用；孕妇慎用",
        "quantity": 320,
        "unit": "g",
        "price": 32,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "竹叶",
        "alias": "淡竹叶",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘、淡",
        "meridian": "归心、胃、小肠经",
        "efficacy": "清热除烦，生津，利尿",
        "indications": "热病烦渴，口疮尿赤",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阴虚火旺，骨蒸潮热者忌用",
        "quantity": 350,
        "unit": "g",
        "price": 18,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "淡竹叶",
        "alias": "竹叶麦冬",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘、淡",
        "meridian": "归心、胃、小肠经",
        "efficacy": "清热泻火，除烦止渴，利尿通淋",
        "indications": "热病烦渴，小便短赤涩痛，口舌生疮",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "脾胃虚寒者慎服",
        "quantity": 300,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "栀子",
        "alias": "山栀子",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、肺、三焦经",
        "efficacy": "泻火除烦，清热利湿，凉血解毒；外用消肿止痛",
        "indications": "热病心烦，湿热黄疸，淋证涩痛，血热吐衄，目赤肿痛，火毒疮疡；外治扭挫伤痛",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 360,
        "unit": "g",
        "price": 25,
        "min_stock": 42,
        "notes": ""
    },
    {
        "name": "夏枯草",
        "alias": "夏枯球",
        "category": "清热药",
        "nature": "寒",
        "taste": "辛、苦",
        "meridian": "归肝、胆经",
        "efficacy": "清肝泻火，明目，散结消肿",
        "indications": "目赤肿痛，目珠夜痛，头痛眩晕，瘰疬，瘿瘤，乳痈，乳癖，乳房胀痛",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚弱者慎服",
        "quantity": 320,
        "unit": "g",
        "price": 28,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "决明子",
        "alias": "草决明",
        "category": "清热药",
        "nature": "微寒",
        "taste": "甘、苦、咸",
        "meridian": "归肝、大肠经",
        "efficacy": "清热明目，润肠通便",
        "indications": "目赤涩痛，羞明多泪，头痛眩晕，目暗不明，大便秘结",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒及便溏者慎服",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "黄芩",
        "alias": "条芩",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、胆、脾、大肠、小肠经",
        "efficacy": "清热燥湿，泻火解毒，止血，安胎",
        "indications": "湿温、暑湿，胸闷呕恶，湿热痞满，泻痢，黄疸，肺热咳嗽，高热烦渴，血热吐衄，痈肿疮毒，胎动不安",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "脾胃虚寒者不宜使用",
        "quantity": 420,
        "unit": "g",
        "price": 32,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "黄连",
        "alias": "鸡爪连",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、脾、胃、肝、胆、大肠经",
        "efficacy": "清热燥湿，泻火解毒",
        "indications": "湿热痞满，呕吐吞酸，泻痢，黄疸，高热神昏，心火亢盛，心烦不寐，心悸不宁，血热吐衄，目赤，牙痛，消渴，痈肿疔疮；外治湿疹，湿疮，耳道流脓",
        "usage": "煎服",
        "dosage": "2-5g",
        "contraindication": "脾胃虚寒者忌用；阴虚津伤者慎用",
        "quantity": 280,
        "unit": "g",
        "price": 85,
        "min_stock": 32,
        "notes": "川黄连"
    },
    {
        "name": "黄柏",
        "alias": "川黄柏",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肾、膀胱经",
        "efficacy": "清热燥湿，泻火除蒸，解毒疗疮",
        "indications": "湿热泻痢，黄疸尿赤，带下阴痒，热淋涩痛，脚气痿躄，骨蒸劳热，盗汗，遗精，疮疡肿毒，湿疹湿疮",
        "usage": "煎服",
        "dosage": "3-12g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 320,
        "unit": "g",
        "price": 45,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "龙胆",
        "alias": "龙胆草",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肝、胆经",
        "efficacy": "清热燥湿，泻肝胆火",
        "indications": "湿热黄疸，阴肿阴痒，带下，湿疹瘙痒，肝火目赤，耳鸣耳聋，胁痛口苦，强中，惊风抽搐",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "脾胃虚寒者忌用；阴虚津伤者慎用",
        "quantity": 260,
        "unit": "g",
        "price": 55,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "秦皮",
        "alias": "白蜡树皮",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、涩",
        "meridian": "归肝、胆、大肠经",
        "efficacy": "清热燥湿，收涩止痢，止带，明目",
        "indications": "湿热泻痢，赤白带下，目赤肿痛，目生翳膜",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 220,
        "unit": "g",
        "price": 38,
        "min_stock": 26,
        "notes": ""
    },
    {
        "name": "金银花",
        "alias": "忍冬花",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、心、胃经",
        "efficacy": "清热解毒，疏散风热",
        "indications": "痈肿疔疮，喉痹，丹毒，热毒血痢，风热感冒，温病发热",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚疮疡脓清者忌服",
        "quantity": 520,
        "unit": "g",
        "price": 48,
        "min_stock": 60,
        "notes": "河南封丘金银花"
    },
    {
        "name": "连翘",
        "alias": "连壳",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归肺、心、小肠经",
        "efficacy": "清热解毒，消肿散结，疏散风热",
        "indications": "痈疽，瘰疬，乳痈，丹毒，风热感冒，温病初起，温热入营，高热烦渴，神昏发斑，热淋涩痛",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "脾胃虚寒及气虚脓清者不宜",
        "quantity": 450,
        "unit": "g",
        "price": 38,
        "min_stock": 52,
        "notes": "青翘"
    },
    {
        "name": "蒲公英",
        "alias": "婆婆丁",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肝、胃经",
        "efficacy": "清热解毒，消肿散结，利尿通淋",
        "indications": "疔疮肿毒，乳痈，瘰疬，目赤，咽痛，肺痈，肠痈，湿热黄疸，热淋涩痛",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 480,
        "unit": "g",
        "price": 12,
        "min_stock": 55,
        "notes": ""
    },
    {
        "name": "紫花地丁",
        "alias": "地丁草",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、辛",
        "meridian": "归心、肝经",
        "efficacy": "清热解毒，凉血消肿",
        "indications": "疔疮肿毒，痈疽发背，丹毒，毒蛇咬伤",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 320,
        "unit": "g",
        "price": 18,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "野菊花",
        "alias": "野黄菊花",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦、辛",
        "meridian": "归肝、心经",
        "efficacy": "清热解毒，泻火平肝",
        "indications": "疔疮痈肿，目赤肿痛，头痛眩晕",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "穿心莲",
        "alias": "一见喜",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、肺、大肠、膀胱经",
        "efficacy": "清热解毒，凉血，消肿",
        "indications": "感冒发热，咽喉肿痛，口舌生疮，顿咳劳嗽，泄泻痢疾，热淋涩痛，痈肿疮疡，蛇虫咬伤",
        "usage": "煎服",
        "dosage": "6-9g",
        "contraindication": "脾胃虚寒者不宜",
        "quantity": 280,
        "unit": "g",
        "price": 25,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "大青叶",
        "alias": "蓝叶",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、胃经",
        "efficacy": "清热解毒，凉血消斑",
        "indications": "热病高热，神昏，发斑发疹，痄腮，喉痹，丹毒，痈肿",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 350,
        "unit": "g",
        "price": 18,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "板蓝根",
        "alias": "靛青根",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、胃经",
        "efficacy": "清热解毒，凉血利咽",
        "indications": "温疫时毒，发热咽痛，温毒发斑，痄腮，烂喉丹痧，大头瘟疫，丹毒，痈肿",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "体虚而无实火热毒者忌服",
        "quantity": 420,
        "unit": "g",
        "price": 22,
        "min_stock": 48,
        "notes": ""
    },
    {
        "name": "鱼腥草",
        "alias": "蕺菜",
        "category": "清热药",
        "nature": "微寒",
        "taste": "辛",
        "meridian": "归肺经",
        "efficacy": "清热解毒，消痈排脓，利尿通淋",
        "indications": "肺痈吐脓，痰热喘咳，热痢，热淋，痈肿疮毒",
        "usage": "煎服",
        "dosage": "15-25g",
        "contraindication": "虚寒证者忌服",
        "quantity": 380,
        "unit": "g",
        "price": 15,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "射干",
        "alias": "乌扇",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺经",
        "efficacy": "清热解毒，消痰，利咽",
        "indications": "热毒痰火郁结，咽喉肿痛，痰涎壅盛，咳嗽气喘",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "孕妇慎用",
        "quantity": 300,
        "unit": "g",
        "price": 32,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "山豆根",
        "alias": "苦豆根",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归肺、胃经",
        "efficacy": "清热解毒，消肿利咽",
        "indications": "火毒蕴结，乳蛾喉痹，咽喉肿痛，齿龈肿痛，口舌生疮",
        "usage": "煎服",
        "dosage": "3-6g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 250,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "白头翁",
        "alias": "野丈人",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归胃、大肠经",
        "efficacy": "清热解毒，凉血止痢",
        "indications": "热毒血痢，阴痒带下",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "虚寒泻痢者忌用",
        "quantity": 300,
        "unit": "g",
        "price": 38,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "马齿苋",
        "alias": "马齿菜",
        "category": "清热药",
        "nature": "寒",
        "taste": "酸",
        "meridian": "归肝、大肠经",
        "efficacy": "清热解毒，凉血止血，止痢",
        "indications": "热毒血痢，痈肿疔疮，湿疹，丹毒，蛇虫咬伤，便血，痔血，崩漏下血",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者忌服",
        "quantity": 350,
        "unit": "g",
        "price": 10,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "生地黄",
        "alias": "生地",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归心、肝、肾经",
        "efficacy": "清热凉血，养阴生津",
        "indications": "热入营血，温毒发斑，吐血衄血，热病伤阴，舌绛烦渴，津伤便秘，阴虚发热，骨蒸劳热，内热消渴",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾虚湿滞者忌用",
        "quantity": 380,
        "unit": "g",
        "price": 42,
        "min_stock": 45,
        "notes": "怀生地黄"
    },
    {
        "name": "玄参",
        "alias": "元参",
        "category": "清热药",
        "nature": "微寒",
        "taste": "甘、苦、咸",
        "meridian": "归肺、胃、肾经",
        "efficacy": "清热凉血，滋阴降火，解毒散结",
        "indications": "热入营血，温毒发斑，热病伤阴，舌绛烦渴，津伤便秘，骨蒸劳嗽，目赤，咽痛，白喉，瘰疬，痈肿疮毒",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者不宜",
        "quantity": 320,
        "unit": "g",
        "price": 35,
        "min_stock": 38,
        "notes": "浙玄参"
    },
    {
        "name": "牡丹皮",
        "alias": "丹皮",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦、辛",
        "meridian": "归心、肝、肾经",
        "efficacy": "清热凉血，活血化瘀",
        "indications": "热入营血，温毒发斑，吐血衄血，夜热早凉，无汗骨蒸，经闭痛经，跌扑伤痛，痈肿疮毒",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "血虚有寒者慎用",
        "quantity": 300,
        "unit": "g",
        "price": 48,
        "min_stock": 35,
        "notes": "凤丹皮"
    },
    {
        "name": "赤芍",
        "alias": "红芍药",
        "category": "清热药",
        "nature": "微寒",
        "taste": "苦",
        "meridian": "归肝经",
        "efficacy": "清热凉血，散瘀止痛",
        "indications": "热入营血，温毒发斑，吐血衄血，目赤肿痛，肝郁胁痛，经闭痛经，癥瘕腹痛，跌扑损伤，痈肿疮疡",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "血寒经闭者不宜",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "青蒿",
        "alias": "香蒿",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、辛",
        "meridian": "归肝、胆经",
        "efficacy": "清虚热，除骨蒸，解暑热，截疟，退黄",
        "indications": "温邪伤阴，夜热早凉，阴虚发热，骨蒸劳热，暑邪发热，疟疾寒热，湿热黄疸",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚弱者慎用",
        "quantity": 360,
        "unit": "g",
        "price": 22,
        "min_stock": 42,
        "notes": ""
    },
    {
        "name": "白薇",
        "alias": "白龙须",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、咸",
        "meridian": "归胃、肝、肾经",
        "efficacy": "清热凉血，利尿通淋，解毒疗疮",
        "indications": "温邪伤营发热，阴虚发热，骨蒸劳热，产后血虚发热，热淋，血淋，痈疽肿毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "脾胃虚寒者不宜",
        "quantity": 260,
        "unit": "g",
        "price": 32,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "地骨皮",
        "alias": "杞根皮",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、肝、肾经",
        "efficacy": "凉血除蒸，清肺降火",
        "indications": "阴虚潮热，骨蒸盗汗，肺热咳嗽，咯血，衄血，内热消渴",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒者忌用",
        "quantity": 280,
        "unit": "g",
        "price": 28,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "大黄",
        "alias": "将军",
        "category": "泻下药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归脾、胃、大肠、肝、心包经",
        "efficacy": "泻下攻积，清热泻火，凉血解毒，逐瘀通经，利湿退黄",
        "indications": "实热积滞便秘，血热吐衄，目赤咽肿，痈肿疔疮，肠痈腹痛，瘀血经闭，产后瘀阻，跌打损伤，湿热痢疾，黄疸尿赤，淋证，水肿；外治烧烫伤",
        "usage": "煎服",
        "dosage": "3-15g",
        "contraindication": "孕妇及月经期、哺乳期慎用",
        "quantity": 350,
        "unit": "g",
        "price": 32,
        "min_stock": 40,
        "notes": "生大黄"
    },
    {
        "name": "芒硝",
        "alias": "朴硝",
        "category": "泻下药",
        "nature": "寒",
        "taste": "咸、苦",
        "meridian": "归胃、大肠经",
        "efficacy": "泻下通便，润燥软坚，清火消肿",
        "indications": "实热积滞，腹满胀痛，大便燥结，肠痈肿痛；外治乳痈，痔疮肿痛",
        "usage": "6-12g，冲入药汁内或开水溶化后服",
        "dosage": "6-12g",
        "contraindication": "孕妇慎用",
        "quantity": 280,
        "unit": "g",
        "price": 18,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "番泻叶",
        "alias": "泻叶",
        "category": "泻下药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归大肠经",
        "efficacy": "泻热行滞，通便，利水",
        "indications": "热结积滞，便秘腹痛，水肿胀满",
        "usage": "煎服",
        "dosage": "2