import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import Database

additional_medicines = [
    {
        "name": "南沙参",
        "alias": "泡参",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "养阴清肺，益胃生津，化痰，益气",
        "indications": "肺热燥咳，阴虚劳嗽，干咳痰黏，胃阴不足，食少呕吐，气阴不足，烦热口干",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "虚寒证忌服",
        "quantity": 200,
        "unit": "g",
        "price": 28,
        "min_stock": 25,
        "notes": ""
    },
    {
        "name": "百合",
        "alias": "白百合",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归心、肺经",
        "efficacy": "养阴润肺，清心安神",
        "indications": "阴虚燥咳，劳嗽咳血，虚烦惊悸，失眠多梦，精神恍惚",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "风寒咳嗽及中寒便溏者忌服",
        "quantity": 300,
        "unit": "g",
        "price": 35,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "麦冬",
        "alias": "麦门冬",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘、微苦",
        "meridian": "归心、肺、胃经",
        "efficacy": "养阴润肺，益胃生津，清心除烦",
        "indications": "肺燥干咳，阴虚痨嗽，喉痹咽痛，津伤口渴，内热消渴，心烦失眠，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒泄泻，胃有痰饮湿浊及暴感风寒咳嗽者均忌服",
        "quantity": 350,
        "unit": "g",
        "price": 42,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "天冬",
        "alias": "天门冬",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、苦",
        "meridian": "归肺、肾经",
        "efficacy": "养阴润燥，清肺生津",
        "indications": "肺燥干咳，顿咳痰黏，腰膝酸痛，骨蒸潮热，内热消渴，热病津伤，咽干口渴，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒，食少便溏者忌服",
        "quantity": 280,
        "unit": "g",
        "price": 38,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "石斛",
        "alias": "林兰",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归胃、肾经",
        "efficacy": "益胃生津，滋阴清热",
        "indications": "热病津伤，口干烦渴，胃阴不足，食少干呕，病后虚热不退，阴虚火旺，骨蒸劳热，目暗不明，筋骨痿软",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "温热病早期阴未伤者、湿温病未化燥者、脾胃虚寒者均禁服",
        "quantity": 180,
        "unit": "g",
        "price": 120,
        "min_stock": 20,
        "notes": "铁皮石斛"
    },
    {
        "name": "玉竹",
        "alias": "葳蕤",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "养阴润燥，生津止渴",
        "indications": "肺胃阴伤，燥热咳嗽，咽干口渴，内热消渴",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "痰湿气滞者禁服，脾虚便溏者慎服",
        "quantity": 320,
        "unit": "g",
        "price": 28,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "黄精",
        "alias": "鸡头黄精",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归脾、肺、肾经",
        "efficacy": "补气养阴，健脾，润肺，益肾",
        "indications": "脾胃气虚，体倦乏力，胃阴不足，口干食少，肺虚燥咳，劳嗽咳血，精血不足，腰膝酸软，须发早白，内热消渴",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "中寒泄泻，痰湿痞满气滞者禁服",
        "quantity": 260,
        "unit": "g",
        "price": 45,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "枸杞子",
        "alias": "枸杞",
        "category": "补虚药",
        "nature": "平",
        "taste": "甘",
        "meridian": "归肝、肾经",
        "efficacy": "滋补肝肾，益精明目",
        "indications": "虚劳精亏，腰膝酸痛，眩晕耳鸣，阳痿遗精，内热消渴，血虚萎黄，目昏不明",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "外邪实热，脾虚有湿及泄泻者忌服",
        "quantity": 400,
        "unit": "g",
        "price": 55,
        "min_stock": 45,
        "notes": "宁夏枸杞"
    },
    {
        "name": "墨旱莲",
        "alias": "旱莲草",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、酸",
        "meridian": "归肾、肝经",
        "efficacy": "滋补肝肾，凉血止血",
        "indications": "肝肾阴虚，牙齿松动，须发早白，眩晕耳鸣，腰膝酸软，阴虚血热吐血、衄血、尿血，血痢，崩漏下血，外伤出血",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾肾虚寒者忌服",
        "quantity": 220,
        "unit": "g",
        "price": 25,
        "min_stock": 26,
        "notes": ""
    },
    {
        "name": "女贞子",
        "alias": "冬青子",
        "category": "补虚药",
        "nature": "凉",
        "taste": "甘、苦",
        "meridian": "归肝、肾经",
        "efficacy": "滋补肝肾，明目乌发",
        "indications": "肝肾阴虚，眩晕耳鸣，腰膝酸软，须发早白，目暗不明，内热消渴，骨蒸潮热",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒泄泻及阳虚者忌服",
        "quantity": 240,
        "unit": "g",
        "price": 32,
        "min_stock": 28,
        "notes": ""
    },
    {
        "name": "桑椹",
        "alias": "桑果",
        "category": "补虚药",
        "nature": "寒",
        "taste": "甘、酸",
        "meridian": "归心、肝、肾经",
        "efficacy": "滋阴补血，生津润燥",
        "indications": "肝肾阴虚，眩晕耳鸣，心悸失眠，须发早白，津伤口渴，内热消渴，肠燥便秘",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒便溏者禁服",
        "quantity": 180,
        "unit": "g",
        "price": 48,
        "min_stock": 20,
        "notes": ""
    },
    {
        "name": "龟甲",
        "alias": "龟板",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "咸、甘",
        "meridian": "归肝、肾、心经",
        "efficacy": "滋阴潜阳，益肾强骨，养血补心，固经止崩",
        "indications": "阴虚潮热，骨蒸盗汗，头晕目眩，虚风内动，筋骨痿软，心虚健忘，崩漏经多",
        "usage": "煎服",
        "dosage": "9-24g",
        "contraindication": "脾胃虚寒者忌服，孕妇慎用",
        "quantity": 120,
        "unit": "g",
        "price": 180,
        "min_stock": 15,
        "notes": ""
    },
    {
        "name": "鳖甲",
        "alias": "团鱼盖",
        "category": "补虚药",
        "nature": "微寒",
        "taste": "咸",
        "meridian": "归肝、肾经",
        "efficacy": "滋阴潜阳，退热除蒸，软坚散结",
        "indications": "阴虚发热，骨蒸劳热，阴虚阳亢，头晕目眩，虚风内动，手足瘈疭，经闭，癥瘕，久疟疟母",
        "usage": "煎服",
        "dosage": "9-24g",
        "contraindication": "脾胃虚寒，食少便溏及孕妇禁服",
        "quantity": 100,
        "unit": "g",
        "price": 150,
        "min_stock": 12,
        "notes": ""
    },
    {
        "name": "麻黄",
        "alias": "龙沙",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、微苦",
        "meridian": "归肺、膀胱经",
        "efficacy": "发汗解表，宣肺平喘，利水消肿",
        "indications": "风寒感冒，胸闷喘咳，风水浮肿；蜜麻黄润肺止咳，多用于表证已解，气喘咳嗽",
        "usage": "煎服",
        "dosage": "2-10g",
        "contraindication": "凡表虚自汗、阴虚盗汗及虚喘者均当忌用",
        "quantity": 350,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "桂枝",
        "alias": "柳桂",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、甘",
        "meridian": "归心、肺、膀胱经",
        "efficacy": "发汗解肌，温通经脉，助阳化气，平冲降气",
        "indications": "风寒感冒，脘腹冷痛，血寒经闭，关节痹痛，痰饮，水肿，心悸，奔豚",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "凡外感热病、阴虚火旺、血热妄行等证，均当忌用；孕妇及月经过多者慎用",
        "quantity": 400,
        "unit": "g",
        "price": 22,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "紫苏叶",
        "alias": "苏叶",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、脾经",
        "efficacy": "解表散寒，行气和胃",
        "indications": "风寒感冒，咳嗽呕恶，妊娠呕吐，鱼蟹中毒",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴虚、气虚及温病者慎服",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "生姜",
        "alias": "鲜生姜",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、脾、胃经",
        "efficacy": "解表散寒，温中止呕，化痰止咳，解鱼蟹毒",
        "indications": "风寒感冒，胃寒呕吐，寒痰咳嗽，鱼蟹中毒",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "热盛及阴虚内热者忌服",
        "quantity": 600,
        "unit": "g",
        "price": 8,
        "min_stock": 70,
        "notes": ""
    },
    {
        "name": "香薷",
        "alias": "香茹",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "发汗解表，化湿和中，利水消肿",
        "indications": "暑湿感冒，恶寒发热，头痛无汗，腹痛吐泻，水肿，小便不利",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "表虚有汗及暑热证当忌用",
        "quantity": 280,
        "unit": "g",
        "price": 25,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "荆芥",
        "alias": "假苏",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛",
        "meridian": "归肺、肝经",
        "efficacy": "解表散风，透疹，消疮",
        "indications": "感冒，头痛，麻疹，风疹，疮疡初起；炒炭治便血，崩漏，产后血晕",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "表虚自汗、阴虚头痛忌用",
        "quantity": 420,
        "unit": "g",
        "price": 20,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "防风",
        "alias": "铜芸",
        "category": "解表药",
        "nature": "微温",
        "taste": "辛、甘",
        "meridian": "归膀胱、肝、脾经",
        "efficacy": "祛风解表，胜湿止痛，止痉",
        "indications": "感冒头痛，风湿痹痛，风疹瘙痒，破伤风",
        "usage": "煎服",
        "dosage": "5-10g",
        "contraindication": "阴血亏虚、热病动风者不宜使用",
        "quantity": 380,
        "unit": "g",
        "price": 35,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "羌活",
        "alias": "羌青",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归膀胱、肾经",
        "efficacy": "解表散寒，祛风除湿，止痛",
        "indications": "风寒感冒，头痛项强，风湿痹痛，肩背酸痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "血虚痹痛者忌用；阴虚头痛者慎用",
        "quantity": 320,
        "unit": "g",
        "price": 42,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "白芷",
        "alias": "香白芷",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归胃、大肠、肺经",
        "efficacy": "解表散寒，祛风止痛，宣通鼻窍，燥湿止带，消肿排脓",
        "indications": "感冒头痛，眉棱骨痛，鼻塞流涕，鼻鼽，鼻渊，牙痛，带下，疮疡肿痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴虚血热者忌服",
        "quantity": 360,
        "unit": "g",
        "price": 28,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "细辛",
        "alias": "小辛",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归心、肺、肾经",
        "efficacy": "解表散寒，祛风止痛，通窍，温肺化饮",
        "indications": "风寒感冒，头痛，牙痛，鼻塞流涕，鼻鼽，鼻渊，风湿痹痛，痰饮喘咳",
        "usage": "煎服",
        "dosage": "1-3g",
        "contraindication": "阴虚阳亢头痛、肺燥伤阴干咳者忌用；不宜与藜芦同用",
        "quantity": 180,
        "unit": "g",
        "price": 55,
        "min_stock": 20,
        "notes": "辽细辛"
    },
    {
        "name": "藁本",
        "alias": "藁茇",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归膀胱经",
        "efficacy": "祛风散寒，除湿止痛",
        "indications": "风寒感冒，巅顶疼痛，风湿痹痛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "阴血亏虚、肝阳上亢、火热内盛之头痛者忌服",
        "quantity": 250,
        "unit": "g",
        "price": 38,
        "min_stock": 30,
        "notes": ""
    },
    {
        "name": "苍耳子",
        "alias": "老苍子",
        "category": "解表药",
        "nature": "温",
        "taste": "辛、苦",
        "meridian": "归肺经",
        "efficacy": "散风寒，通鼻窍，祛风湿",
        "indications": "风寒头痛，鼻塞流涕，鼻鼽，鼻渊，风疹瘙痒，湿痹拘挛",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "血虚头痛不宜服用；过量服用易致中毒",
        "quantity": 280,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "辛夷",
        "alias": "木笔花",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "散风寒，通鼻窍",
        "indications": "风寒头痛，鼻塞流涕，鼻鼽，鼻渊",
        "usage": "煎服",
        "dosage": "3-10g",
        "contraindication": "鼻病因于阴虚火旺者忌服",
        "quantity": 220,
        "unit": "g",
        "price": 45,
        "min_stock": 28,
        "notes": ""
    },
    {
        "name": "葱白",
        "alias": "葱茎白",
        "category": "解表药",
        "nature": "温",
        "taste": "辛",
        "meridian": "归肺、胃经",
        "efficacy": "发汗解表，散寒通阳",
        "indications": "风寒感冒，阴盛格阳",
        "usage": "煎服",
        "dosage": "3-9g",
        "contraindication": "表虚多汗者忌服",
        "quantity": 300,
        "unit": "g",
        "price": 12,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "石膏",
        "alias": "细石",
        "category": "清热药",
        "nature": "大寒",
        "taste": "甘、辛",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，除烦止渴",
        "indications": "外感热病，高热烦渴，肺热喘咳，胃火亢盛，头痛，牙痛",
        "usage": "煎服",
        "dosage": "15-60g",
        "contraindication": "脾胃虚寒及血虚、阴虚发热者忌用",
        "quantity": 520,
        "unit": "g",
        "price": 8,
        "min_stock": 60,
        "notes": ""
    },
    {
        "name": "寒水石",
        "alias": "凝水石",
        "category": "清热药",
        "nature": "寒",
        "taste": "辛、咸",
        "meridian": "归心、胃、肾经",
        "efficacy": "清热泻火，利窍，消肿",
        "indications": "热病烦渴，丹毒烫伤",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚寒者忌服",
        "quantity": 280,
        "unit": "g",
        "price": 22,
        "min_stock": 32,
        "notes": ""
    },
    {
        "name": "知母",
        "alias": "连母",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦、甘",
        "meridian": "归肺、胃、肾经",
        "efficacy": "清热泻火，滋阴润燥",
        "indications": "外感热病，高热烦渴，肺热燥咳，骨蒸潮热，内热消渴，肠燥便秘",
        "usage": "煎服",
        "dosage": "6-12g",
        "contraindication": "脾胃虚寒，大便溏泄者忌服",
        "quantity": 380,
        "unit": "g",
        "price": 28,
        "min_stock": 45,
        "notes": ""
    },
    {
        "name": "芦根",
        "alias": "苇茎",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，生津止渴，除烦，止呕，利尿",
        "indications": "热病烦渴，肺热咳嗽，肺痈吐脓，胃热呕哕，热淋涩痛",
        "usage": "煎服",
        "dosage": "15-30g",
        "contraindication": "脾胃虚寒者忌服",
        "quantity": 420,
        "unit": "g",
        "price": 15,
        "min_stock": 50,
        "notes": ""
    },
    {
        "name": "天花粉",
        "alias": "瓜蒌根",
        "category": "清热药",
        "nature": "微寒",
        "taste": "甘、微苦",
        "meridian": "归肺、胃经",
        "efficacy": "清热泻火，生津止渴，消肿排脓",
        "indications": "热病烦渴，肺热燥咳，内热消渴，疮疡肿毒",
        "usage": "煎服",
        "dosage": "10-15g",
        "contraindication": "脾胃虚寒，大便溏泄者忌服；不宜与川乌、制川乌、草乌、制草乌、附子同用；孕妇慎用",
        "quantity": 320,
        "unit": "g",
        "price": 32,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "竹叶",
        "alias": "淡竹叶",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘、淡",
        "meridian": "归心、胃、小肠经",
        "efficacy": "清热除烦，生津，利尿",
        "indications": "热病烦渴，口疮尿赤",
        "usage": "煎服",
        "dosage": "6-15g",
        "contraindication": "阴虚火旺，骨蒸潮热者忌用",
        "quantity": 350,
        "unit": "g",
        "price": 18,
        "min_stock": 40,
        "notes": ""
    },
    {
        "name": "淡竹叶",
        "alias": "竹叶麦冬",
        "category": "清热药",
        "nature": "寒",
        "taste": "甘、淡",
        "meridian": "归心、胃、小肠经",
        "efficacy": "清热泻火，除烦止渴，利尿通淋",
        "indications": "热病烦渴，小便短赤涩痛，口舌生疮",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "脾胃虚寒者慎服",
        "quantity": 300,
        "unit": "g",
        "price": 22,
        "min_stock": 35,
        "notes": ""
    },
    {
        "name": "栀子",
        "alias": "山栀子",
        "category": "清热药",
        "nature": "寒",
        "taste": "苦",
        "meridian": "归心、肺、三焦经",
        "efficacy": "泻火除烦，清热利湿，凉血解毒；外用消肿止痛",
        "indications": "热病心烦，湿热黄疸，淋证涩痛，血热吐衄，目赤肿痛，火毒疮疡；外治扭挫伤痛",
        "usage": "煎服",
        "dosage": "6-10g",
        "contraindication": "脾胃虚寒者慎用",
        "quantity": 360,
        "unit": "g",
        "price": 25,
        "min_stock": 42,
        "notes": ""
    },
    {
        "name": "夏枯草",
        "alias": "夏枯球",
        "category": "清热药",
        "nature": "寒",
        "taste": "辛、苦",
        "meridian": "归肝、胆经",
        "efficacy": "清肝泻火，明目，散结消肿",
        "indications": "目赤肿痛，目珠夜痛，头痛眩晕，瘰疬，瘿瘤，乳痈，乳癖，乳房胀痛",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚弱者慎服",
        "quantity": 320,
        "unit": "g",
        "price": 28,
        "min_stock": 38,
        "notes": ""
    },
    {
        "name": "决明子",
        "alias": "草决明",
        "category": "清热药",
        "nature": "微寒",
        "taste": "甘、苦、咸",
        "meridian": "归肝、大肠经",
        "efficacy": "清热明目，润肠通便",
        "indications": "目赤涩痛，羞明多泪，头痛眩晕，目暗不明，大便秘结",
        "usage": "煎服",
        "dosage": "9-15g",
        "contraindication": "脾胃虚寒及便溏者慎服",
        "quantity": 380,
        "unit": "g",
        "price": 18,
        "min_stock": 45,
        "notes": ""
    }
]

def add_more_medicines():
    print("=" * 60)
    print("添加更多药材到300味")
    print("=" * 60)
    
    db = Database()
    
    added = 0
    errors = 0
    
    for medicine in additional_medicines:
        try:
            existing = db.fetchone(
                "SELECT id FROM medicines WHERE name = ?", 
                (medicine['name'],)
            )
            
            if not existing:
                print(f"添加: {medicine['name']}...", end="")
                
                db.execute('''
                    INSERT INTO medicines 
                    (name, alias, category, nature, taste, meridian, 
                     efficacy, indications, usage, dosage, contraindication, notes)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (
                    medicine['name'],
                    medicine.get('alias', ''),
                    medicine.get('category', ''),
                    medicine.get('nature', ''),
                    medicine.get('taste', ''),
                    medicine.get('meridian', ''),
                    medicine.get('efficacy', ''),
                    medicine.get('indications', ''),
                    medicine.get('usage', ''),
                    medicine.get('dosage', ''),
                    medicine.get('contraindication', ''),
                    medicine.get('notes', '')
                ))
                
                med_id = db.fetchone(
                    "SELECT id FROM medicines WHERE name = ?", 
                    (medicine['name'],)
                )[0]
                
                db.execute('''
                    INSERT INTO inventory 
                    (medicine_id, quantity, unit, price, min_stock, notes)
                    VALUES (?, ?, ?, ?, ?, ?)
                ''', (
                    med_id,
                    medicine.get('quantity', 0),
                    medicine.get('unit', 'g'),
                    medicine.get('price', 0),
                    medicine.get('min_stock', 10),
                    medicine.get('notes', '')
                ))
                
                added += 1
                print("成功！")
            else:
                print(f"跳过: {medicine['name']} (已存在)")
                
        except Exception as e:
            errors += 1
            print(f"错误: {medicine['name']} - {str(e)}")
            continue
    
    print("\n" + "=" * 60)
    print(f"添加完成！新增 {added} 味，错误 {errors} 味")
    print("=" * 60)
    
    med_count = db.fetchone("SELECT COUNT(*) FROM medicines")[0]
    inv_count = db.fetchone("SELECT COUNT(*) FROM inventory")[0]
    
    print(f"\n当前药材总数: {med_count}")
    print(f"当前库存总数: {inv_count}")
    
    db.close()

if __name__ == '__main__':
    add_more_medicines()
    input("\n按任意键退出...")